teamforage/forage-android-sdk

.github/workflows/CI.yaml

Updating the Integration Test to refer to the [mobile-qa-tests](https://github.com/teamforage/mobile-qa-tests) repo and run the android sdk qa tests that are found in that repo.
- NO - updating a github action

Update GH action to use new consolidated repo for integration tests

---

.github/workflows/CI.yaml

The retry logic was removed from the github action that ran QA tests in this repo. These tests aren't the most resilient, so the retry logic is often necessary to get them to complete. I looked through a few of the past failed runs and many of them failed because 1 random test had an issue. This should fix our problems.

Fix broken script

---

README.md
forage-android/src/main/java/com/joinforage/forage/android/ForageSDK.kt
forage-android/src/main/java/com/joinforage/forage/android/ForageSDKApi.kt
forage-android/src/main/java/com/joinforage/forage/android/model/PaymentMethod.kt
forage-android/src/main/java/com/joinforage/forage/android/network/TokenizeCardService.kt
forage-android/src/test/java/com/joinforage/forage/android/fixtures/CreatePaymentMethodFixtures.kt
forage-android/src/test/java/com/joinforage/forage/android/network/TokenizeCardServiceTest.kt
forage-android/src/test/resources/fixtures/payment/methods/successful_create_nonreusable_payment_method.json

As described in [this](https://linear.app/joinforage/issue/FX-268/android-add-the-reusable-flag-to-post-payment-method-endpoint) ticket, adding optional reusable param to tokenizeCard calls. Reusable will be set to true by default, maintaining the current behavior.
Added test to validate successful response with or without param
NOTE: Calls to tokenize card should now be returning `reusable` as well (see [here](https://linear.app/joinforage/issue/COR-341/include-reusable-in-response-from-createpaymentmethod-view)), so we should update `PaymentMethod` as well as all the fixtures to include that param, but not sure if that falls within the scope of this diff:
```
val response =
PaymentMethod.ModelMapper.from((paymentMethodResponse as ForageApiResponse.Success).data) …
```

[FX-268] Add optional reusable param to tokenizeCard

---

forage-android/src/main/java/com/joinforage/forage/android/ui/BTVaultWrapper.kt
forage-android/src/main/java/com/joinforage/forage/android/ui/ForagePANEditText.kt
forage-android/src/main/java/com/joinforage/forage/android/ui/ForagePINEditText.kt
forage-android/src/main/java/com/joinforage/forage/android/ui/ForageUI.kt
forage-android/src/main/java/com/joinforage/forage/android/ui/VGSVaultWrapper.kt
forage-android/src/main/java/com/joinforage/forage/android/ui/VaultWrapper.kt

The recommended way of accessing observable state on
Forage Elements (e.g. PAN/PIN) is via `.getElementState()`.
We don't want to add surface-level attributes to ForageElements
because they inherit from so many other Android View's and there
is a strong chance of name collisions; promoting
`.getElementState()` gives us our own namespace and distinct
abstraction
- NO. Does not affect any functionality. This PR eliminates two fields for reading state

BREAKING: remove isValid, isEmpty from ForageUI

---

forage-android/src/main/java/com/joinforage/forage/android/ui/BTVaultWrapper.kt
forage-android/src/main/java/com/joinforage/forage/android/ui/ForagePANEditText.kt
forage-android/src/main/java/com/joinforage/forage/android/ui/ForagePINEditText.kt
forage-android/src/main/java/com/joinforage/forage/android/ui/ForageUI.kt
forage-android/src/main/java/com/joinforage/forage/android/ui/VGSVaultWrapper.kt
forage-android/src/main/java/com/joinforage/forage/android/ui/VaultWrapper.kt

Connects the `ElementStateManager` service to the `ForagePINEditText` and `ForagePANEditText` views
- NO. The `ElementStateManger` service has its own tests in #53. Since this PR is connecting the service to the view, that would require end-2-end automated tests, which is out-of-scope given our need to ship this to GoPuff asap. I've included screen demos showcasing working functionality for VGS and BT.
Here are two demo videos that showcase the focus, blur, and change event functionalities for VGS and Basis Theory being the vault providers
https://github.com/teamforage/forage-android-sdk/assets/12377418/48258f58-acd6-4b30-a7c0-6eccf3ac4d8b
https://github.com/teamforage/forage-android-sdk/assets/12377418/c15fba32-f3d5-4def-aad0-f4c93bda020d

PAN and PIN expose `focus`, `blur`, and `change` event listeners & state-query

---

forage-android/src/main/java/com/joinforage/forage/android/ui/BTVaultWrapper.kt
forage-android/src/main/java/com/joinforage/forage/android/ui/ForagePANEditText.kt
forage-android/src/main/java/com/joinforage/forage/android/ui/ForagePINEditText.kt
forage-android/src/main/java/com/joinforage/forage/android/ui/ForageUI.kt
forage-android/src/main/java/com/joinforage/forage/android/ui/VGSVaultWrapper.kt
forage-android/src/main/java/com/joinforage/forage/android/ui/VaultWrapper.kt

Within the init method we use an if-else so vault is
guaranteed to point to either VGS or BT. By making `vault`
non-null we can clean up the file and make it easier to read

Make vault field non-null

---

README_DEV.md

This will help developers verify their coverage locally instead of relying exclusively on the GitHub Action.

[POP-92] Add instructions for generating PR line coverage locally to README_DEV

---

forage-android/src/main/java/com/joinforage/forage/android/ui/ForagePANEditText.kt

Get rid of `TextInputLayout related` error visuals
The visuals were driven by the setting of `textInputLayout.error` in the
`afterTextChanged` method. However, since we are no longer setting the
`.error` attribute, it would follow that we should remove the
`textInputLayoutErrorEnabled` in the `init{ ... }` method since GoPuff
should still be able to set that if they so choose
We don't need to release the second PR in this stack (#61), since that PR can be merged independently at a later point.
- NO - still don't support `espresso` QA-tests so now way to do automated QA tests on Android
The screenshot below demonstrates `ForagePANEditText` have a non-null `validationError` and the red error text present under the input field, which indicates the successful removal of the errors.

Get rid of `TextInputLayout` related error visuals

---

forage-android/build.gradle
forage-android/src/main/java/com/joinforage/forage/android/core/Log.kt
gradle.properties

Add the Forage SDK version to the build config and append it to all logs.

[FX-443] Expose version in build config and add to logs

---

forage-android/src/main/java/com/joinforage/forage/android/ForageSDK.kt
forage-android/src/main/java/com/joinforage/forage/android/core/element/state/PanElementStateManager.kt
forage-android/src/main/java/com/joinforage/forage/android/ui/ForagePANEditText.kt
forage-android/src/test/java/com/joinforage/forage/android/core/element/state/PanElementStateManagerTest.kt

1. Reverted the changes done in #65 
2. Adds support for whitelisted EBT PANs for `ForagePANEditText` when environment is not "prod"
The commits are very detailed so read one by one for more context.
- YES - adds many dozens of unit tests to verify the whitelisting and Strict IIN validation logic
Video demo of the whitelisted cards and StateIIN cards being accepted as valid
https://github.com/teamforage/forage-android-sdk/assets/12377418/53eed848-b377-4120-aff8-36a67460d662

[FX-456] Support Whitelisted PAN Cards in Non-Prod environments

---

forage-android/build.gradle
forage-android/src/main/java/com/joinforage/forage/android/core/element/state/PanElementStateManager.kt
forage-android/src/main/java/com/joinforage/forage/android/model/StateIIN.kt
forage-android/src/main/java/com/joinforage/forage/android/ui/ForagePANEditText.kt
forage-android/src/main/java/com/joinforage/forage/android/ui/FormatPanTextWatcher.kt
forage-android/src/test/java/com/joinforage/forage/android/ui/FormatPanTextWatcherTest.kt

1. Introduces the `FormatPanTextWatcher` 
2. Updates the `ForagePANEditText` to use the `ForagePanTextWatcher` to format its input
- See [linear ticket](https://linear.app/joinforage/issue/FX-404/android-support-dynamically-updating-the-mask-of-ebt-card-numbers)
- ⚠️  Currently, formatting the PAN text makes the `ForagePANEditText` no longer a Numbers-only input, so adding formatting results in the regular keyboard popping up instead of the numbers-only keyboard that was showing up before.
- YES - this PR added ~30 unit tests to ensure that formatting works in many different scenarios
Demo showing:
1. 4{14} white listed cards are Valid
2. 5{14} white listed cards are Valid
3. 9{4} white listed cards are Valid
4. 654321 white listed cards are Valid
5. State IIN Validation 
6. 16 PAN …

[FX-404] Support dynamic PAN masking based on StateIIN

---

forage-android/src/main/java/com/joinforage/forage/android/ui/ForagePANEditText.kt
forage-android/src/main/java/com/joinforage/forage/android/ui/FormatPanTextWatcher.kt
forage-android/src/test/java/com/joinforage/forage/android/ui/FormatPanTextWatcherTest.kt

There are two updates to the `TextInputEditText` when the user types
something. 1) is the actual user's update and 2) is the update that
reformats the input field based on the lastest changes.
Previously, the `ForagePANEditText` was invoking the changEvent callback
for each of these, which is suboptimal. To fix this, we defer the
responsibility of knowing to invoke the user's registered callback to
the `FormatPanTextWatcher` since it holds the source of truth to
- YES - adds a test to the `FormatPanTextWatcher` to ensure that the callback gets invoked exactly once and passes the formatted value
https://github.com/teamforage/forage-android-sdk/assets/12377418/ae995307-99fa-461f-8db3-f2ecbdb1ce8a

Make sure that onChangeEventHandler gets fired once

---

forage-android/src/main/java/com/joinforage/forage/android/ui/FormatPanTextWatcher.kt
forage-android/src/test/java/com/joinforage/forage/android/ui/FormatPanTextWatcherTest.kt

Updates the default spacing of PANs to be groups of 4 digits when they do not match StateIIN
- YES - updates unit tests that had previously assumed no transformation
Demo showcasing formatting and that you can (try to) submit even very invalid numbers
https://github.com/teamforage/forage-android-sdk/assets/12377418/c3d1b444-e54c-473e-ae7b-e79ad64377ea

Space all PAN inputs by 4 digits by default

---

forage-android/src/main/java/com/joinforage/forage/android/ui/ForagePANEditText.kt

Previously, we did not use the `keyListener` attribute of the
`TextInputEditText` and that would cause the app to crash because the
PanFormatTextWatcher would insert whitespaces that were disallowed.
This combination of attributes seems to fix the issue and has everything
playing nicely together.
- NO - this is just a view-level configuration

Set ForagePANEditText keyboard to numbers

---

forage-android/src/main/java/com/joinforage/forage/android/ui/BTVaultWrapper.kt
forage-android/src/main/java/com/joinforage/forage/android/ui/ForagePANEditText.kt
forage-android/src/main/java/com/joinforage/forage/android/ui/ForagePINEditText.kt
forage-android/src/main/java/com/joinforage/forage/android/ui/ForageUI.kt
forage-android/src/main/java/com/joinforage/forage/android/ui/VGSVaultWrapper.kt
forage-android/src/main/java/com/joinforage/forage/android/ui/VaultWrapper.kt

Adds support for `.clearText()` method to all `ForageElements` as requested by GoPuff [here](https://joinforage.slack.com/archives/C04FQM5F2DA/p1693327253627219)
- NO. We need (and don't have) expresso to create automated test on the UI
Demo of `ForagePANEditText.clearText()` working as expected
https://github.com/teamforage/forage-android-sdk/assets/12377418/81166a18-253e-4ff7-9e89-f7d2424f63a4
Demo of `ForagePINEditText.clearText()` working as expected
https://github.com/teamforage/forage-android-sdk/assets/12377418/803a5b68-291e-4e2f-abe7-8eb009907411

Add support for `clearText` to PIN and PAN elements.

---

forage-android/build.gradle
gradle.properties

Bumpt to v2.0.6 to release to `.clearText` to GoPuff today

Bump version for 2.0.6 release

---

forage-android/build.gradle

Bump Basis Theory package to `v2.5.0` to support [overriding text-align](https://github.com/Basis-Theory/basistheory-android/pull/92).
- We're going to wait for @dleis612 to come back before merging this in case there were reasons we did not want to keep the Basis Theory package up to date with the latest
- Tested PIN capture using BT on my machine and it worked so seems fine

Bump BT to version 2.5.0

---

forage-android/src/main/java/com/joinforage/forage/android/ui/BTVaultWrapper.kt
forage-android/src/main/java/com/joinforage/forage/android/ui/VGSVaultWrapper.kt

Align PIN textfield on center.
- NO. Not that big of a change.

[SYM-104] Inner private-text alignment for PIN field should be center aligned

---

.github/workflows/CI.yaml

See title.
Appears to want to retry failed tests with the second line but won't do so because the error code of the first failure will short-circuit the Github Action. Use `|| true` to always return 0 and let the second attempt have the final say. 
Test change.
CI change only.
Merge.

Don't short circuit integ test before retry

---

forage-android/src/main/java/com/joinforage/forage/android/network/data/CapturePaymentRepository.kt
forage-android/src/main/java/com/joinforage/forage/android/network/model/ForageApiResponse.kt
forage-android/src/main/java/com/joinforage/forage/android/network/model/Message.kt
forage-android/src/test/java/com/joinforage/forage/android/model/SQSErrorTest.kt
sample-app/src/main/java/com/joinforage/android/example/ui/complete/flow/payment/capture/FlowCapturePaymentViewModel.kt
sample-app/src/main/java/com/joinforage/android/example/ui/complete/flow/payment/capture/model/FlowCapturePaymentUIState.kt
sample-app/src/main/res/layout/fragment_flow_capture_payment.xml

GoPuff would like the ability to easily read the latest value of the EBT Cash and SNAP values of a PaymentMethod if the PaymentMethod yield an `ebt_error_51` (insufficient funds) error when trying to capture a payment. (see [slack convo](https://joinforage.slack.com/archives/C04FQM5F2DA/p1693922478724489)).
This PR introduces an opaque `.details` field on the `ForageError` that will be `null` for be an instantiation of `ErrorMessageDetails`. Right the only instance is `ErrorMessageDetails.InsufficientFundsDetails` but this can be straightforwardly extended if, in the future, other `ForageError`s ought to carry their own information.
************************************Specifically, this PR does:************************************
- display the full ForageError, including the new details …

Add details field to ForageErrorObj

---

forage-android/src/main/java/com/joinforage/forage/android/ui/ForagePANEditText.kt

Allow the `ForagePANEditText` to support users copy/pasting their PAN numbers.
I [verified with Ygor](https://joinforage.slack.com/archives/C056QGRF6S3/p1692652253893609) that by having the `ForagePANEditText` stop implementing the `ActionMode.Callback` interface, that the input would start supporting the copy/paste menu after a longpress. Previously, this was expressly disabled.
No tests because this is entirely in the view-layer and we don't have tests for that yet
https://github.com/teamforage/forage-android-sdk/assets/12377418/2bbc8227-8892-4bf2-a21c-61337fc0dc1d

Make long-clickable & stop implementing ActionMode.Callback

---

forage-android/src/main/java/com/joinforage/forage/android/ui/BTVaultWrapper.kt
forage-android/src/main/java/com/joinforage/forage/android/ui/VGSVaultWrapper.kt
forage-android/src/main/res/values/attrs.xml

- Add background and border color for PIN input field.
- ❌ The reviewer should manually test the changes in this PR. 
Custom:
<table><tr>
<td> 
<p align="center" style="padding: 10px">
<br>
<em style="color: grey">VGS</em>
</p> 
</td>
<td> 
<p align="center">
<br>
<em style="color: grey">BT</em>
</p> 
</td>
</tr></table>
Default:
<table><tr>
<td> 
<p align="center" style="padding: 10px">
<br>
<em style="color: grey">VGS</em>
</p> 
</td>
<td> 
<p align="center">
<br>
<em style="color: grey">BT</em>
</p> 
</td>
</tr></table>

[SYM-114] Support custom background + border color for PIN input field

---

forage-android/src/main/java/com/joinforage/forage/android/ui/ForagePANEditText.kt
forage-android/src/main/java/com/joinforage/forage/android/ui/ForagePINEditText.kt
forage-android/src/main/java/com/joinforage/forage/android/ui/ForagePanTextUtils.kt
forage-android/src/main/java/com/joinforage/forage/android/ui/ForageUI.kt
forage-android/src/main/java/com/joinforage/forage/android/ui/FormatPanTextWatcher.kt
forage-android/src/main/res/values/attrs.xml
sample-app/src/main/res/values/colors.xml
sample-app/src/main/res/values/styles.xml

Add support for border width, border color and corner radius for PAN field.
- ❌ I've added unit tests for this change.
- ❌ The reviewer should manually test the changes in this PR.
Focused:
<table><tr>
<td> 
<p align="center" style="padding: 10px">
<br>
<em style="color: grey">Default</em>
</p> 
</td>
<td> 
<p align="center">
<br>
<em style="color: grey">Custom</em>
</p> 
</td>
</tr></table>
Unfocused:
<table><tr>
<td> 
<p align="center" style="padding: 10px">
<br>
<em style="color: grey">Default</em>
</p> 
</td>
<td> 
<p align="center">
<br>
<em style="color: grey">Custom</em>
</p> 
</td>
</tr></table>

[SYM-115] Support border width, color and corner radius for PAN

---

forage-android/src/main/java/com/joinforage/forage/android/Utils.kt
forage-android/src/main/java/com/joinforage/forage/android/network/data/CapturePaymentRepository.kt
forage-android/src/main/java/com/joinforage/forage/android/network/data/CheckBalanceRepository.kt
forage-android/src/test/java/com/joinforage/forage/android/utils/UtilsTest.kt

Adding +/- 25ms jitter to polling so that we can avoid a thundering herd issue if our clients retry all at the same time. Now all retries to polling will have some randomness added to their delay interval.

[POP-180] Adding jitter to retry logic

---

forage-android/src/main/java/com/joinforage/forage/android/ui/AbstractForageElement.kt
forage-android/src/main/java/com/joinforage/forage/android/ui/ForagePANEditText.kt
forage-android/src/main/java/com/joinforage/forage/android/ui/ForagePINEditText.kt
sample-app/src/main/java/com/joinforage/android/example/ui/catalog/CatalogFragment.kt

The linear ticket is [here](https://linear.app/joinforage/issue/FX-596/android-make-sure-that-setforageconfig-can-be-called-multiple-times). Also, see the commit messages for detailed explanations of changes
One of the design goals of introducing `setForageConfig` is to be able to handle `sessionToken` refresh or even update `merchantId` on the fly. This means `setForageConfig` needs to be safe to be called multiple times. Right now, it is not safe to call multiple times. It will actually crash the app:
- ❌ I've added unit tests for this change.  In theory, there is logic in here that can be extracted out into a unit test. However, given the modifications this PR makes to `CatalogFragment.kt`, we gain some confidence that the logic in `AbstractForageElement` is working correctly. So, I …

[FX-596] Make `setForageConfig` safe to call multiple times

---

forage-android/src/main/java/com/joinforage/forage/android/ui/ForagePANEditText.kt
forage-android/src/main/res/values/attrs.xml
sample-app/src/main/res/values/styles.xml

Linear ticket [here](https://linear.app/joinforage/issue/FX-593/android-convert-floats-dimensions-for-panstrokewidth)
Dimensions are the appropriate unit for visuals with a length component, so they scale correctly to various screen sizes. Float don't scale at all
- ❌ I've added unit tests for this change. No tests because we don't have anything set up to test view layer
- ❌ The reviewer should manually test the changes in this PR.  No need to manually test. the demo should suffice
Demo showing the different stroke sizes based on `focused` and `unfocused` state
https://github.com/teamforage/forage-android-sdk/assets/12377418/27c97baf-30a1-493f-aa8a-eae912660d6d
It can be rolled out as is. NOTE that it is a breaking change, but gopuff is expecting it, and it is small so I"m thinking we …

[FX-593] Convert floats to dimensions for styling

---

forage-android/src/main/java/com/joinforage/forage/android/collect/BTPinCollector.kt
forage-android/src/main/java/com/joinforage/forage/android/collect/VGSPinCollector.kt
forage-android/src/main/java/com/joinforage/forage/android/network/ForageConstants.kt

If the PIN field is invalid when someone attempts to submit, don't hit our 3rd party APIs and instead just return that the PIN was invalid.
- ❌ I've added unit tests for this change. -> I WILL BE ADDING A QA TEST FOR THIS
- ✅ The reviewer should manually test the changes in this PR.

[FX-599] Don't hit VGS or BT when invalid PIN submitted

---

.github/workflows/CI.yaml
.github/workflows/Lint.yaml

* Modifies the `CI.yaml` file to refer to `debug` build instead of `sandbox` for unit tests and `stanging` for Appium.
* Modifies `Lint.yaml` to refer to `debug` build instead of `cert`
We no longer have flavors. Instead, we have the standard `release` and `debug` builds that are the default for all Android apps. Technically, it does not matter right now whether we use the `debug` or the `prod` build since `forage-android`'s environment is determined by the `sessionToken` that it gets passed at runtime and [`mobile-qa-tests` reference staging](https://github.com/teamforage/mobile-qa-tests/blob/7f15c11934c8211a38baff87a30ee69b04191031/helpers/forage_api.py#L8-L9). Just to be safe - in case anything changes in the future - I pointed both CI and Lint to the `debug` build.
Given that this PR …

Testing changes to CI workflow in seperate file

---

README.md

Drop "A Note on Build Variants" section from the README.md
Now that we have dropped build flavors, we no longer need to mention it in the README.md
- ❌ I've added unit tests for this change.  No tests - just a README update
- The reviewer should manually test the changes in this PR.  No need to test locally since you can see the rendered README in github
N/A
This PR can be merged directly into main after #113, #114, and #115 get merged together as one large PR into `main`. Ideally we are not also merging this PR into a mega PR since it is atomic unlike #113 + #114 + #115, which are not atomic individual but are atomic together

Drop refernce to Build Variants in README.md

---

forage-android/build.gradle
forage-android/src/main/java/com/joinforage/forage/android/core/EnvConfig.kt

Bump to v3.2.0. Release notes [here](https://www.notion.so/joinforage/Release-Tracker-94d996c2c7e14501a96d54722a89532e?pvs=4#c72b0e452e964812b4e606f9fdd6a953)

Bump to v3.2.0 for dropping build flavors

---

forage-android/build.gradle
forage-android/src/main/java/com/joinforage/forage/android/core/EnvConfig.kt

Danny spotted [a way](https://github.com/Basis-Theory/basistheory-android/blob/0a1435feb66c4732714ff9bb1b412636b63f7edf/lib/build.gradle#L16) for us to declare the `PUBLISH_VERSION` in exactly one place and have it exposed at run time via `BuildConfig`.
Have a single source of truth for the release version. Previously, we were updating two variables in the code with every release
- ❌ I've added unit tests for this change.  No test because its a build related change
- ❌ The reviewer should manually test the changes in this PR.  No need since its a simple change and you can see that it works in the demo
I tried to highlight the salient lines of code via the red breakpoints:
1. I changed the publish version to something new "3.3.0" which is different form our "3.20"
2. I'm exposing the …

Create single source of truth for the Publish Version

---

forage-android/src/main/java/com/joinforage/forage/android/LDManager.kt
forage-android/src/main/java/com/joinforage/forage/android/network/data/CapturePaymentRepository.kt
forage-android/src/main/java/com/joinforage/forage/android/network/data/CheckBalanceRepository.kt
forage-android/src/main/java/com/joinforage/forage/android/ui/ForagePINEditText.kt
forage-android/src/test/java/com/joinforage/forage/android/network/data/LaunchDarklyTest.kt

Reading the `iso-polling-wait-intervals` feature flag value to determine how long to wait between each polling retry.
Make polling more configurable instead of waiting 1 second every poll attempt. Leads to faster response times from our clients.

[POP-76] Configure polling with feature flag

---

forage-android/src/main/java/com/joinforage/forage/android/ForageSDK.kt
forage-android/src/main/java/com/joinforage/forage/android/network/EncryptionKeyService.kt
forage-android/src/main/java/com/joinforage/forage/android/network/ForageConstants.kt
forage-android/src/main/java/com/joinforage/forage/android/network/MessageStatusService.kt
forage-android/src/main/java/com/joinforage/forage/android/network/PaymentMethodService.kt
forage-android/src/main/java/com/joinforage/forage/android/network/PaymentService.kt
forage-android/src/main/java/com/joinforage/forage/android/network/TokenizeCardService.kt
forage-android/src/test/java/com/joinforage/forage/android/core/env/EnvConfigTest.kt
forage-android/src/test/java/com/joinforage/forage/android/network/EncryptionKeyServiceTest.kt
forage-android/src/test/java/com/joinforage/forage/android/network/MessageStatusServiceTest.kt
forage-android/src/test/java/com/joinforage/forage/android/network/TokenizeCardServiceTest.kt
forage-android/src/test/java/com/joinforage/forage/android/network/data/CapturePaymentRepositoryTest.kt
forage-android/src/test/java/com/joinforage/forage/android/network/data/CheckBalanceRepositoryTest.kt

This PR is associated with [removing `ForageConstant.kt`'s dependence on `StopgapGlobalState`](https://www.notion.so/joinforage/Pre-GoPuff-Launch-Cleanup-Proposal-aa5c5caf4a6747fc930ad511e83b79b6?pvs=4#357ef83068174aabba9256e14e36198b), part of the remaining cleanup work associated with Android 3.0
`ForageConstant.kt`'s depended on `StopgapGlobalState` because of `BASE_URL`. However, `BASE_URL` is only directly consumed by `ForageSDK`, which means we make moving the related logic directly into `ForageSDK` by parsing the `sessionToken` to extract the `baseUrl`
- ✅ and ❌. I added unit tests to ensure surface if any of the `EncConfig` `baseUrl`s ever become malformed because we are unable to get the compiler's guarantee of non-null values or that it won't throw runtime errors. We had a …

[FX-677] Remove ForageConstants dependence on StopgapGlobalState

---

forage-android/src/main/java/com/joinforage/forage/android/core/telemetry/Log.kt
forage-android/src/main/java/com/joinforage/forage/android/ui/AbstractForageElement.kt
forage-android/src/main/java/com/joinforage/forage/android/ui/ForagePANEditText.kt
forage-android/src/main/java/com/joinforage/forage/android/ui/ForagePINEditText.kt
forage-android/src/test/java/com/joinforage/forage/android/core/telemetry/metrics/ResponseMonitorTest.kt

This PR is associated with [removing `Log.kt`'s dependence on `StopgapGlobalState`](https://www.notion.so/joinforage/Pre-GoPuff-Launch-Cleanup-Proposal-aa5c5caf4a6747fc930ad511e83b79b6?pvs=4#13dcc917df71402190f0b96fd8a4ac2a), part of the remaining cleanup work associated with Android 3.0
`Log.kt`'s depended on `StopgapGlobalState` because of the Datadog client key and we were able to remove that dependence by having `Log.initializeDD(...)` accept a `ForageConfig` as a param
- ❌.  No novel unit tests were add but I updated the unit tests in accordance with the changes made
- ❌ It's not necessary to manually test these changes as the CI tests will flag if there's an issue with these changes.
This can be rolled out once approved!

[FX-678] Remove Forage Log's dependence on StopgapGlobalState

---

forage-android/src/main/java/com/joinforage/forage/android/LDManager.kt
forage-android/src/main/java/com/joinforage/forage/android/network/data/CapturePaymentRepository.kt
forage-android/src/main/java/com/joinforage/forage/android/network/data/CheckBalanceRepository.kt
forage-android/src/main/java/com/joinforage/forage/android/ui/ForagePINEditText.kt
forage-android/src/test/java/com/joinforage/forage/android/network/data/LaunchDarklyTest.kt

This PR is associated with [removing `LDManager.kt`'s dependence on `StopgapGlobalState`](https://www.notion.so/joinforage/Pre-GoPuff-Launch-Cleanup-Proposal-aa5c5caf4a6747fc930ad511e83b79b6?pvs=4#31c155cd4bdb40d78f8e78295c7b2bc5), part of the remaining cleanup work associated with Android 3.0
`LDManage.kt` depended on `StopgapGlobalState` for the Launch Darkly client key. We were able to remove that dependence by having `LDMangager.initialize(...)` accept an `LDConfig`, which will have the LD client key already set.
- ❌ While the code coverage will not change with this PR, I did introduce two additional unit tests to explicitly test the helpder function responsible for mapping the primary vault traffic flag to a Vault Provider
- ❌ It's not necessary to manually test these changes as the …

[FX-681] Remove LDManager's dependence on StopgapGlobalState

---

.github/workflows/CI.yaml

Right now the only way to run CI tests on a branch is to create a PR. It would be create if we could just run the CI tests on an arbitrary branch rather than PR-intended branches as some branches are just meant for exploration
Can be merged in whenever

Add support for manual triggering of CI Github action

---

forage-android/src/main/java/com/joinforage/forage/android/LDManager.kt
sample-app/src/main/java/com/joinforage/android/example/ui/complete/flow/tokenize/FlowTokenizeFragment.kt
sample-app/src/main/res/layout/fragment_flow_tokenize.xml

Update the sample app to leverage the newly exposed `state.details.derivedCardInfo.usState` field.
Keep the sample app in sync with visual functionality that our customers can use.
- ❌ Not unit tests because this is the Sample App, which does not support unit tests at present
- ✅ I'd recommend playing around with it just to see but the demo should suffice.
Sample app has been updated to display the `usState`
https://github.com/teamforage/forage-android-sdk/assets/12377418/1c15b6bc-8575-48c3-9f29-3aaa6c187f51
This PR needs to be merged into #133. It is not standalone.

Update sample app to show usState of PAN

---

forage-android/consumer-rules.pro
forage-android/proguard-rules.pro
forage-android/src/main/java/com/joinforage/forage/android/collect/BTPinCollector.kt
sample-app/build.gradle
sample-app/proguard-rules.pro

Create a data class for the BT body parameters and add a directive to the `consumer-rules.pro` file so that people who use Forage don't obfuscate the object.
GoPuff (and probably others in the future) use ProGuard or a similar tool that obfuscates their code. Since they consume our SDK, this also obfuscates _OUR_ code. When this happens, the BT integration fails because the `card_number_token` and `pin` fields are changed to `a` and `b`. These names are important and must stay consistent.
I have tested this change locally by running ProGuard on our sample app and replicating the issue. After adding the `consumer-rules.pro` directive, I re-ran the build process and can see that the code is not obfuscated. Then, I ran the release .apk file and was able to interact with BT.

[FX-792] Add consumer-rules to Forage SDK

---

.github/workflows/CI.yaml

to prevent CI check concurrency issues
https://github.com/teamforage/mobile-qa-tests/pull/35 should be merged first

[FX-839] Use dynamic Browserstack custom ID 

---

sample-app/src/main/java/com/joinforage/android/example/MainActivity.kt
sample-app/src/main/java/com/joinforage/android/example/ui/pos/POSFragment.kt
sample-app/src/main/java/com/joinforage/android/example/ui/pos/POSViewModel.kt
sample-app/src/main/res/menu/bottom_nav_menu.xml
sample-app/src/main/res/navigation/mobile_navigation.xml
sample-app/src/main/res/values/strings.xml

Adds a link to a POS flow that will eventually be built out for FIS certification. For now, it just goes to an empty view. 
Creating a place to build out the rest of the flow. I'm new to Android dev so this seemed like a low-stakes way for me to get started.
- Doesn't really seem like the kind of thing to have a unit test for since it's just Android navigation functionality.
- ✅ The reviewer should manually test the changes in this PR.
- Run the sample app on a test device (either physical or virtual) and see the POS nav item. Tap the item to be taken to a new empty view. 
https://github.com/teamforage/forage-android-sdk/assets/11556475/b25a05e5-50b9-48a3-8b14-23796cabbbb4
I'm not sure how we want to roll this out, or if we just want to branch …

[FX-880] Add POS option to bottom nav that goes to empty view

---

.gitignore
CONTRIBUTING.md
build.gradle

- Adds SDK reference docs generator [using Dokka](https://github.com/Kotlin/dokka)
```
./gradlew dokkaHtml # generate reference-docs/
cd reference-docs/ # 
open index.html # or npx http-serve to open the docs website.
```
- [Separate inherited members in docs](https://github.com/teamforage/forage-android-sdk/pull/90/commits/789a53d7bb974c8b53d032b7428fe06a08842c00) 
- Helps clean up the docs pages where we inherit from chunky classes like LinearLayout.
- With the latest version of Dokka, we cannot hide these inherited members entirely, we can only separate them.
No, gradle change.
Used netlify drop to deploy "temporary" hosted version of these docs to review them.
- Can be released as-is and allow us to manually generate docs
- Created a ticket to make the [internal code internal …

[FX-518] Can auto-generate docs for forage-android

---

sample-app/src/main/java/com/joinforage/android/example/pos/receipts/CPayPrinter.kt
sample-app/src/main/java/com/joinforage/android/example/pos/receipts/ReceiptFormatting.kt
sample-app/src/main/java/com/joinforage/android/example/pos/receipts/ReceiptLayout.kt
sample-app/src/main/java/com/joinforage/android/example/pos/receipts/ReceiptLayoutLine.kt
sample-app/src/main/java/com/joinforage/android/example/pos/receipts/ReceiptLinePart.kt
sample-app/src/main/java/com/joinforage/android/example/pos/receipts/ReceiptPrinter.kt
sample-app/src/main/java/com/joinforage/android/example/ui/pos/POSFragment.kt
sample-app/src/main/java/com/joinforage/android/example/ui/pos/ReceiptView.kt
sample-app/src/main/res/layout/fragment_pos.xml

I debated splitting this PR up but into multiple PRs for ease of consumption but since this PR is strictly adding new services, and  because I organized the commits into stories, I opted to have one medium-large PR for simplicity. I'd be happy to split up this PR if it makes life easier for anyone.
This PR introduces an internal representation of receipt. The highest level is the `ReceiptLayout`, which represents an entire receipt that can be printed or displayed. `ReceiptLayout`s are composed of `ReceiptLayoutLines`, which represent a single line on a receipt. It is common (and necessary) for receipts to depict multiple columns of text, so `ReceiptLayoutLines` are composed of `ReceiptLinePart`s, which are the smallest and atomic units of receipts.
This PR also introduces:
- a …

[FX-751] Add Support to Print and Display Receipts

---

forage-android/src/main/java/com/joinforage/forage/android/ForageSDK.kt
forage-android/src/main/java/com/joinforage/forage/android/core/telemetry/Log.kt
forage-android/src/main/java/com/joinforage/forage/android/network/PollingService.kt
forage-android/src/main/java/com/joinforage/forage/android/network/data/CapturePaymentRepository.kt
forage-android/src/main/java/com/joinforage/forage/android/network/data/CheckBalanceRepository.kt
forage-android/src/main/java/com/joinforage/forage/android/network/model/Message.kt
forage-android/src/test/java/com/joinforage/forage/android/mock/MockLogger.kt
forage-android/src/test/java/com/joinforage/forage/android/mock/MockRepository.kt
forage-android/src/test/java/com/joinforage/forage/android/network/data/CapturePaymentRepositoryTest.kt

de-dupe polling across payment capture and balance check
will be used for refund as well
- DRY up across balance check, capture and refund
- ✅ unit tests cover polling path and pass
Can be released as-is ; `PollingService` has further room for improvement, but this is a first step

Introduce PollingService

---

forage-android/src/main/java/com/joinforage/forage/android/collect/AbstractVaultSubmitter.kt
forage-android/src/main/java/com/joinforage/forage/android/collect/BasisTheoryPinSubmitter.kt
forage-android/src/main/java/com/joinforage/forage/android/collect/VaultProxyRequest.kt
forage-android/src/main/java/com/joinforage/forage/android/collect/VgsPinSubmitter.kt
forage-android/src/main/java/com/joinforage/forage/android/network/model/ForageApiResponse.kt
forage-android/src/main/java/com/joinforage/forage/android/pos/PosVaultRequestParams.kt

- Introduce
- `AbstractVaultSubmitter`
- `VgsPinSubmitter`
- `BasisTheoryPinSubmitter`
Sought inspiration from @devinmorgan's design doc and his draft PR #129 🎉 
- Improve maintainability of PIN submission logic (across capturePayment, deferPaymentCapture, checkBalance, refundPayment, and so on.)
- Lay foundation for new refund PIN submission
- Lay foundation for implementing `ForageVaultSubmitter`
- ✅  Plugged into `CheckBalanceRepository` locally and tests (that cover VGS responses) passed
- Will add unit tests for the new code in either this PR or a follow-up one!
This PR can be released as-is
The PR will be followed by an "Add `RefundPaymentRepository`" PR that handles the polling using the new `PollingService` from #157 and the abstract submitter from this PR
- I will eventually …

Add Abstract PIN submitters

---

sample-app/src/main/java/com/joinforage/android/example/ui/pos/POSComposeApp.kt
sample-app/src/main/java/com/joinforage/android/example/ui/pos/POSViewModel.kt
sample-app/src/main/java/com/joinforage/android/example/ui/pos/data/POSUIState.kt
sample-app/src/main/java/com/joinforage/android/example/ui/pos/network/PosApiService.kt
sample-app/src/main/java/com/joinforage/android/example/ui/pos/screens/ActionSelectionScreen.kt
sample-app/src/main/java/com/joinforage/android/example/ui/pos/screens/BalanceInquiryScreen.kt
sample-app/src/main/java/com/joinforage/android/example/ui/pos/screens/ManualPANEntryScreen.kt
sample-app/src/main/java/com/joinforage/android/example/ui/pos/ui/ComposableForagePANEditText.kt
sample-app/src/main/res/values/strings.xml

Adds a screen for manual PAN entry via the Balance Inquiry flow. We should be able to reuse this screen for the Payment Capture as well when we get there. The Submit button uses our SDK to tokenize the EBT card.
POS Certification App
https://github.com/teamforage/forage-android-sdk/assets/11556475/16c8f1b2-4a1c-4018-884f-d8f1eca78250

[FX-739] Create EBT payment method by manual pan entry

---

sample-app/src/main/java/com/joinforage/android/example/ui/pos/POSComposeApp.kt
sample-app/src/main/java/com/joinforage/android/example/ui/pos/screens/ActionSelectionScreen.kt
sample-app/src/main/java/com/joinforage/android/example/ui/pos/screens/balance/BalanceInquiryScreen.kt
sample-app/src/main/java/com/joinforage/android/example/ui/pos/screens/balance/BalanceResultScreen.kt
sample-app/src/main/java/com/joinforage/android/example/ui/pos/screens/payment/PaymentTypeSelectionScreen.kt
sample-app/src/main/java/com/joinforage/android/example/ui/pos/screens/shared/ManualPANEntryScreen.kt
sample-app/src/main/java/com/joinforage/android/example/ui/pos/screens/shared/PinEntryScreen.kt
sample-app/src/main/res/values/strings.xml

Adds a screen where a user can select which type of payment/purchase to perform once they've chosen to create a payment/purchase from the main action screen
This also does some housekeeping on how screen files are organized since we're gonna have a lot of them
POS Cert app
https://github.com/teamforage/forage-android-sdk/assets/11556475/00679f67-712f-4cb8-82e0-3d62632f7afd

[FX-831] Create Screen to select the type of payment/purchase to perform

---

sample-app/src/main/java/com/joinforage/android/example/ui/pos/POSComposeApp.kt
sample-app/src/main/java/com/joinforage/android/example/ui/pos/POSFragment.kt
sample-app/src/main/java/com/joinforage/android/example/ui/pos/POSViewModel.kt
sample-app/src/main/java/com/joinforage/android/example/ui/pos/data/POSUIState.kt

Switches to use `ForageTerminalSDK` for pan tokenization and pin submission instead of `ForageSDK`. This required hoisting the view model up to the Fragment (previously it was created by the POSComposeApp and thus not available in the Fragment) so we could store the terminal ID in the view model and UI state in the success/error callbacks when setting up the CPay SDK.
POS Cert App
No visual changes other than you should see the terminal ID on the main POS screen if there is a terminal attached
Needs verification on terminal, but assuming it works, can be merged as-is

[FX-987] & [FX-988] Use ForageTerminalSDK for PAN tokenization & PIN submission instead of ForageSDK

---

sample-app/src/main/java/com/joinforage/android/example/ui/pos/POSComposeApp.kt
sample-app/src/main/java/com/joinforage/android/example/ui/pos/POSViewModel.kt
sample-app/src/main/java/com/joinforage/android/example/ui/pos/data/POSUIState.kt
sample-app/src/main/java/com/joinforage/android/example/ui/pos/network/PosApiService.kt
sample-app/src/main/java/com/joinforage/android/example/ui/pos/screens/shared/ManualPANEntryScreen.kt
sample-app/src/main/java/com/joinforage/android/example/ui/pos/screens/shared/PinEntryScreen.kt
sample-app/src/main/java/com/joinforage/android/example/ui/pos/ui/ComposableForagePANEditText.kt
sample-app/src/main/java/com/joinforage/android/example/ui/pos/ui/ComposableForagePINEditText.kt

[House ForageConfig info](https://github.com/teamforage/forage-android-sdk/pull/171/commits/ff3579d5ee96cddcb1024686707d9a826f59474d)
I think the `POSUIState` could be a good home for the `merchantId`
and the `sessionToken`, which together constitute the
`ForageConfig` info. The wins that I see are:
1. easier to work with the `forageConfig` because a single method
/ getting on `POSUIState` will house the `forageConfig`
Previously, to pass `forageConfig` to the `ForageTerminalSDK`,
we needed to assemble the `ForageConfig` object ourselves
2. now there is a single file that developers can copy/paste the
the `sessionToken` and `merchantId` into instead of needing
to change values across two files

House ForageConfig info in POSUIState

---

sample-app/src/main/java/com/joinforage/android/example/pos/k9sdk/K9SDK.kt
sample-app/src/main/java/com/joinforage/android/example/ui/pos/POSComposeApp.kt
sample-app/src/main/java/com/joinforage/android/example/ui/pos/POSViewModel.kt
sample-app/src/main/java/com/joinforage/android/example/ui/pos/data/POSUIState.kt

[Move terminalId to POSComposeApp](https://github.com/teamforage/forage-android-sdk/pull/172/commits/0ea4a6af8ef9cad2db8b8267db2992becb803a40) 
`terminalId` is similar to `sessionToken` and `merchantId` in that
it likely only gets set once with the initial fetch of merchant
details and then, afterwards, will not need to be set again. It
could follow from this that `terminalId` should live alongside
`merchantId` and `sessionToken` inside `POSUIState`.
I am not opposed to `terminalId` ultimately living in
`POSUIState`. However, reading the `terminalId` from the K9SDK
is an asynchronous process because we need to wait for the
K9SDK to finish initializing before we can read the `terminalId`
value.
It was not readily apparent to me how we would request the K9SDK
to initialize once and only …

Move terminalId to POSComposeApp

---

sample-app/src/main/java/com/joinforage/android/example/ui/pos/POSComposeApp.kt
sample-app/src/main/java/com/joinforage/android/example/ui/pos/POSViewModel.kt
sample-app/src/main/java/com/joinforage/android/example/ui/pos/screens/balance/BalanceInquiryScreen.kt
sample-app/src/main/java/com/joinforage/android/example/ui/pos/screens/shared/MagSwipePANEntryScreen.kt
sample-app/src/main/res/values/strings.xml

Introduces the `MagSwipePANEntryScreen.kt` composable and modifies `POSComposeApp.kt` to use the `MagSwipePANEntryScreen.kt` in order to support magnetic swiping for PAN entry in Balance Inquiries
https://linear.app/joinforage/issue/FX-742/scene-create-ebt-payment-method-by-swiping-card
- ❌  Mostly manipulated UI and CPay SDK. Plus the end to end flow works so didn't feel the time spent writing tests was urgent for now
- ❌ The combination of passing CI + the demo is sufficient for this. Feel free to try locally if you want though! 
https://github.com/teamforage/forage-android-sdk/assets/12377418/c4b492ac-392a-44a1-8352-005257fd4652
This needs to be merged in after #172

[FX-742] Create MagSwipe PAN Reader Component (adds to Balance Inquiry flow)

---

sample-app/src/main/java/com/joinforage/android/example/ui/pos/POSComposeApp.kt
sample-app/src/main/java/com/joinforage/android/example/ui/pos/POSViewModel.kt
sample-app/src/main/java/com/joinforage/android/example/ui/pos/data/POSUIState.kt
sample-app/src/main/java/com/joinforage/android/example/ui/pos/data/PosPaymentRequest.kt
sample-app/src/main/java/com/joinforage/android/example/ui/pos/network/PosApiService.kt
sample-app/src/main/java/com/joinforage/android/example/ui/pos/screens/payment/EBTSnapPurchaseScreen.kt
sample-app/src/main/java/com/joinforage/android/example/ui/pos/screens/payment/PaymentResultScreen.kt
sample-app/src/main/java/com/joinforage/android/example/ui/pos/screens/payment/PaymentTypeSelectionScreen.kt
sample-app/src/main/java/com/joinforage/android/example/ui/pos/screens/shared/PANMethodSelectionScreen.kt
sample-app/src/main/java/com/joinforage/android/example/ui/pos/ui/ScreenWithBottomRow.kt
sample-app/src/main/res/values/strings.xml

Supports a SNAP payment on a manually entered or swiped EBT card. Just dumps the response data into a text field for now. We'll need to connect it up to the receipt code in a future PR.
https://linear.app/joinforage/issue/FX-744/story-snap-purchase-flow-on-a-created-ebt-card
- ❌ Just getting basic functionality built out
- ❌ Demo video should be sufficient for manual entry, but we might want to confirm it on the terminal to make sure swiped entry works
https://github.com/teamforage/forage-android-sdk/assets/11556475/55670622-9f78-455d-a361-04928da10ce1

[FX-744] Story: SNAP purchase flow on a created EBT card

---

sample-app/src/main/java/com/joinforage/android/example/ui/pos/POSComposeApp.kt
sample-app/src/main/java/com/joinforage/android/example/ui/pos/data/PosPaymentRequest.kt
sample-app/src/main/java/com/joinforage/android/example/ui/pos/screens/payment/EBTCashPurchaseScreen.kt
sample-app/src/main/java/com/joinforage/android/example/ui/pos/screens/payment/PaymentTypeSelectionScreen.kt
sample-app/src/main/res/values/strings.xml

Adds support for an EBT Cash purchase to the POS Cert app
https://linear.app/joinforage/issue/FX-745/story-cash-purchase-flow-on-a-created-ebt-card
- ❌ Just building out the basic functionality
- ❌ Demo should be sufficient for manual entry but we may want to test swiped entry on the actual terminal
https://github.com/teamforage/forage-android-sdk/assets/11556475/c6423a5f-4dad-40de-bbc9-030e296a5daa

[FX-745] Story: EBT Cash purchase flow on a created EBT card

---

sample-app/src/main/java/com/joinforage/android/example/ui/pos/POSViewModel.kt
sample-app/src/main/java/com/joinforage/android/example/ui/pos/data/POSUIState.kt
sample-app/src/main/java/com/joinforage/android/example/ui/pos/network/PosApiService.kt

Modify the `PosApiService` so that the baseUrl is determined at runtime based on the value of the `sessionToken` or `authToken` passed.
Previously the baseUrl was hardcoded to `dev`, which was fine for local Android development. However, we also need the ability to test the Sample App in the `cert` environment for the actual FIS Cert testing as well as preparing for that.
The CI tests passing + the demo below give sufficient confidence for now.
(will attach via github)
Can be released as is

Infer api baseUrl from sessionToken

---

sample-app/src/main/java/com/joinforage/android/example/ui/pos/POSComposeApp.kt
sample-app/src/main/java/com/joinforage/android/example/ui/pos/data/PosPaymentRequest.kt
sample-app/src/main/java/com/joinforage/android/example/ui/pos/screens/payment/EBTCashPurchaseWithCashBackScreen.kt
sample-app/src/main/java/com/joinforage/android/example/ui/pos/screens/payment/PaymentTypeSelectionScreen.kt
sample-app/src/main/res/values/strings.xml

Adds the ability to initiate a cash purchase with cash back transaction in the POS Cert App. _Note:_ This currently doesn't succeed due to backend changes needed, but the call appears to be correct based on the Linear ticket.
https://linear.app/joinforage/issue/FX-749/story-cash-purchase-with-cash-back-flow
- ❌ Just getting basic functionality in place
- ❌ We'll need to verify this succeeds once the backend changes are in place
https://github.com/teamforage/forage-android-sdk/assets/11556475/d5f7c966-33bb-4206-9901-658c36c91b45
Can be merged as-is since the call failing doesn't affect the other flows and we catch the error

[FX-749] Story: Cash purchase with cash back flow

---

sample-app/src/main/java/com/joinforage/android/example/ui/pos/POSComposeApp.kt
sample-app/src/main/java/com/joinforage/android/example/ui/pos/data/PosPaymentRequest.kt
sample-app/src/main/java/com/joinforage/android/example/ui/pos/screens/payment/EBTCashWithdrawalScreen.kt
sample-app/src/main/java/com/joinforage/android/example/ui/pos/screens/payment/PaymentTypeSelectionScreen.kt
sample-app/src/main/res/values/strings.xml

Adds support for initiating an EBT Cash Withdrawal transaction to the POS Cert App. _Note:_ This currently doesn't succeed due to backend changes needed, but the call appears to be correct based on the Linear ticket.
https://linear.app/joinforage/issue/FX-748/story-cash-withdrawal-flow
- ❌ Just getting basic functionality in place
- ❌ We'll need to verify this succeeds once the backend changes are in place
https://github.com/teamforage/forage-android-sdk/assets/11556475/d8c0895c-742f-4648-8912-2cc716f45955
Can be merged as-is since the call failing doesn't affect the other flows and we catch the error

[FX-748] Story: EBT cash withdrawal flow

---

forage-android/build.gradle
forage-android/consumer-rules.pro
forage-android/src/main/java/com/joinforage/forage/android/ForageSDK.kt
forage-android/src/main/java/com/joinforage/forage/android/network/data/CapturePaymentRepository.kt
forage-android/src/main/java/com/joinforage/forage/android/network/data/CheckBalanceRepository.kt
forage-android/src/main/java/com/joinforage/forage/android/network/data/DeferPaymentCaptureRepository.kt
forage-android/src/main/java/com/joinforage/forage/android/pos/PosRefundPaymentRepository.kt
forage-android/src/main/java/com/joinforage/forage/android/pos/PosVaultRequestParams.kt
forage-android/src/main/java/com/joinforage/forage/android/ui/ForagePINEditText.kt
forage-android/src/main/java/com/joinforage/forage/android/vault/AbstractVaultSubmitter.kt
forage-android/src/main/java/com/joinforage/forage/android/vault/BTPinCollector.kt
forage-android/src/main/java/com/joinforage/forage/android/vault/BasisTheoryPinSubmitter.kt
forage-android/src/main/java/com/joinforage/forage/android/vault/PinCollector.kt
forage-android/src/main/java/com/joinforage/forage/android/vault/VGSPinCollector.kt
forage-android/src/main/java/com/joinforage/forage/android/vault/VaultProxyRequest.kt
forage-android/src/main/java/com/joinforage/forage/android/vault/VgsPinSubmitter.kt
forage-android/src/test/java/com/joinforage/forage/android/network/data/BTPinCollectorTest.kt
forage-android/src/test/java/com/joinforage/forage/android/network/data/TestPinCollector.kt
forage-android/src/test/java/com/joinforage/forage/android/network/data/VGSPinCollectorTest.kt
forage-android/src/test/java/com/joinforage/forage/android/vault/BasisTheoryPinSubmitterTest.kt
forage-android/src/test/java/com/joinforage/forage/android/vault/VgsPinSubmitterTest.kt

Can serve as reference for writing `ForagePinSubmitter` tests @dleis612 
Will follow-up with PRs for `AbstractVaultSubmitter.kt` and `RefundPaymentRepository.kt`

[FX-976] Add Vault pin submitter tests

---

sample-app/src/main/java/com/joinforage/android/example/ui/pos/POSComposeApp.kt
sample-app/src/main/java/com/joinforage/android/example/ui/pos/POSViewModel.kt
sample-app/src/main/java/com/joinforage/android/example/ui/pos/data/POSUIState.kt
sample-app/src/main/java/com/joinforage/android/example/ui/pos/network/PosApiService.kt
sample-app/src/main/java/com/joinforage/android/example/ui/pos/screens/ActionSelectionScreen.kt
sample-app/src/main/java/com/joinforage/android/example/ui/pos/screens/voids/VoidPaymentScreen.kt
sample-app/src/main/java/com/joinforage/android/example/ui/pos/screens/voids/VoidRefundScreen.kt
sample-app/src/main/java/com/joinforage/android/example/ui/pos/screens/voids/VoidResultScreen.kt
sample-app/src/main/java/com/joinforage/android/example/ui/pos/screens/voids/VoidTypeSelectionScreen.kt
sample-app/src/main/res/values/strings.xml

Adds the flow for voiding payments and refunds. I was able to successfully test voiding a payment ([link](https://api.dev.joinforage.app/admin/api/payment/17107/change/)) but I don't have a refund on my merchant to attempt to void yet. I did try it with a refund from another merchant and got a valid response from the server, but it was a 404 since that refund ref doesn't exist on my merchant. I'll make sure to test voiding a refund before we actually merge this
https://linear.app/joinforage/issue/FX-820/scene-choose-to-void-a-payment-or-a-refund
- ❌ Just building out basic functionality
- ❌ Demo video should suffice for voiding a payment, will need to void a refund first before we merge
https://github.com/teamforage/forage-android-sdk/assets/11556475/fa119755-89b7-4296-aacf-f8bb7bdaac35 …

[FX-820] Scene: Choose to void a payment or a refund

---

forage-android/src/main/java/com/joinforage/forage/android/vault/AbstractVaultSubmitter.kt
forage-android/src/test/java/com/joinforage/forage/android/mock/MockLogger.kt
forage-android/src/test/java/com/joinforage/forage/android/pos/ForageTerminalSDKTest.kt
forage-android/src/test/java/com/joinforage/forage/android/vault/AbstractVaultSubmitterTest.kt

- Adds unit tests for `AbstractVaultSubmitter.kt`
- verifies incomplete pin error condition
- verifies encryption keys + vault tokens parsing
- verifies metrics logging
Can be released as-is.

[FX-1015] Add more unit tests for AbstractVaultSubmitter

---

.gitignore
forage-android/src/main/java/com/joinforage/forage/android/ForageSDKInterface.kt
forage-android/src/main/java/com/joinforage/forage/android/pos/ForageTerminalSDK.kt
forage-android/src/main/java/com/joinforage/forage/android/pos/PosMethodParams.kt
forage-android/src/main/java/com/joinforage/forage/android/ui/AbstractForageElement.kt
forage-android/src/main/java/com/joinforage/forage/android/ui/ForageElement.kt
forage-android/src/main/java/com/joinforage/forage/android/ui/ForagePANEditText.kt
forage-android/src/main/java/com/joinforage/forage/android/ui/ForagePINEditText.kt
forage-android/src/test/java/com/joinforage/forage/android/pos/ForageTerminalSDKTest.kt

- Introduce `ForageElement#setPosForageConfig` and `PosForageConfig` ; helps us use custom logic for loading vault provider-related elements.
- Added comments and validation in case the merchant uses the wrong method.
- gitignore `.idea` directory
- fix comments (for merchant ID, reference `ForageElement` instead of `AbstractForageElement`)
- [See design proposal doc](https://www.notion.so/joinforage/Handling-SDK-vault-routing-for-Toast-integration-f4b8aa60776640e9a7de013f48c13ea3#ca06e1abcf9b47f0a1c1ec5d7f3d8b9e)
- flipped flags in launchdarkly and tested against sample app
- wrote unit tests
- checked logs
- PATCH-level change
- Will eventually be followed by PR for ensuring POS transactions go through rosetta
- ⚠️  @devinmorgan the certification app should be updated to use …

Introduce setPosForageConfig

---

forage-android/src/main/java/com/joinforage/forage/android/ForageSDK.kt

This PR adds a note that FNS regulates balance inquiries for sites that do not offer guest checkout. 
Adding this callout could help save merchant headaches before FNS testing. 
- ❌ | No unit tests are required for comment changes. 
- ✅ | The reviewer should manually test the changes in this PR: 
Checkout my branch, and then: 
```
```

[TW-427] Add FNS callout to checkBalance function

---

sample-app/src/main/java/com/joinforage/android/example/ui/pos/data/PosPaymentRequest.kt

Fixes an issue with the purchase + cashback flow throwing a 400 error. It looks like the `ebtCashAmount` and `cashBackAmounts` are coming into the helper method that generates the payment as strings, then we're trying to add them with `+`, which produces a result that the backend can't coerce to a number. This changes the logic to cast each item to a double, do the math to get the total, then cast that total _back_ to a string to send to the backend.
https://linear.app/joinforage/issue/FX-1052/bug-cash-purchase-with-cashback-gives-400-error
Manually tested the flow in the android emulator
https://github.com/teamforage/forage-android-sdk/assets/11556475/834ab196-5609-45ab-8190-81369592fdbd

[FX-1052] Fix purchase with cashback throwing a 400 error

---

sample-app/src/main/java/com/joinforage/android/example/ui/pos/POSComposeApp.kt
sample-app/src/main/java/com/joinforage/android/example/ui/pos/POSViewModel.kt
sample-app/src/main/res/values/strings.xml

Adds a reset/restart button to the top right of the app bar on all screens that aren't the merchant details or action selection. This will allow testers to jump back to the action selection screen from any subsequent scene regardless of where they are in the flow. It also resets the state to be ready for a new action selection. It persists the merchant details (the assumption being you want to keep the same merchant), but those could easily be changed with another tap of the back arrow after you tap the Reset icon button.
https://linear.app/joinforage/issue/FX-1031/feature-result-pages-should-have-a-return-to-flows-button
Manually tested in the android emulator
https://github.com/teamforage/forage-android-sdk/assets/11556475/e838679d-d26e-45f1-9b35-b6edd1766b15

[FX-1031] feature result pages should have a return to flows button

---

sample-app/src/main/java/com/joinforage/android/example/ui/pos/POSComposeApp.kt

Calls `.clearFocus()` on the PAN or PIN (depending on which flow you're on) to hide the keyboard after submitting either of those fields.
https://linear.app/joinforage/issue/FX-1029/bug-keyboard-does-not-hide-after-pressing-buttons-to-navigate-forward
Manually tested to verify
https://github.com/teamforage/forage-android-sdk/assets/11556475/6fe6fed6-f858-4640-9aab-07384872633a

[FX-1029] Hide keyboard after submitting PAN or PIN

---

sample-app/src/main/java/com/joinforage/android/example/ui/pos/POSComposeApp.kt
sample-app/src/main/java/com/joinforage/android/example/ui/pos/POSViewModel.kt
sample-app/src/main/java/com/joinforage/android/example/ui/pos/data/PosReceipt.kt
sample-app/src/main/java/com/joinforage/android/example/ui/pos/network/PosApiService.kt
sample-app/src/main/java/com/joinforage/android/example/ui/pos/screens/payment/PaymentResultScreen.kt
sample-app/src/main/java/com/joinforage/android/example/ui/pos/screens/refund/RefundResultScreen.kt
sample-app/src/main/java/com/joinforage/android/example/ui/pos/screens/voids/VoidPaymentResultScreen.kt
sample-app/src/main/java/com/joinforage/android/example/ui/pos/screens/voids/VoidRefundResultScreen.kt

Updates void receipts to have accurate status and balances.
In order to facilitate that^ I had to do a fair amount of refactoring. We were relying on the local tokenizedPaymentMethod and paymentRequest in a few places where they sometimes may not be set. Now that we're clearing the app state with the restart button, these values get cleared when starting a new flow. So, for instance, trying to void something would never have a tokenizedPaymentMethod since you never hit a PAN field in that flow. Before this change, we could've had a subtle bug where the receipt could've shown payment method info that wasn't associated with the actual transaction being voided or refunded.
I went through the receipt flows and figured out what data we needed where and what the right source of truth for it …

[FX-1051] Fix issue with void receipts having inaccurate data

---

sample-app/src/main/java/com/joinforage/android/example/pos/receipts/templates/txs/CashPurchaseTxReceipt.kt
sample-app/src/main/java/com/joinforage/android/example/pos/receipts/templates/txs/CashPurchaseWithCashbackTxReceipt.kt
sample-app/src/main/java/com/joinforage/android/example/pos/receipts/templates/txs/CashWithdrawalTxReceipt.kt
sample-app/src/main/java/com/joinforage/android/example/pos/receipts/templates/txs/SnapPurchaseTxReceipt.kt
sample-app/src/main/java/com/joinforage/android/example/ui/pos/POSComposeApp.kt
sample-app/src/main/java/com/joinforage/android/example/ui/pos/POSViewModel.kt
sample-app/src/main/java/com/joinforage/android/example/ui/pos/data/Refund.kt
sample-app/src/main/java/com/joinforage/android/example/ui/pos/screens/payment/PaymentResultScreen.kt
sample-app/src/main/java/com/joinforage/android/example/ui/pos/screens/refund/RefundResultScreen.kt
sample-app/src/main/java/com/joinforage/android/example/ui/pos/screens/voids/VoidPaymentResultScreen.kt
sample-app/src/main/java/com/joinforage/android/example/ui/pos/screens/voids/VoidRefundResultScreen.kt

Updates the receipt logic to handle the situation where the android SDK doesn't poll for sqs messages (simulating what would happen if the terminal was offline), so the backend auto-voids the payment/refund after it goes unacknowledged by the client for 90 seconds.
This is accomplished by showing a button to refetch the relevant entity instead of displaying a receipt. After the auto-void has occurred in the backend, we can tap the button to refetch the data and display the receipt that accurately reflects the now-voided status
https://linear.app/joinforage/issue/FX-828/pos-application-needs-to-offer-a-way-to-get-the-last-payment-refund
- Manually verified the correct behavior in the emulator with the polling disabled in the local android SDK. See demo videos.
This is the behavior when we …

[FX-828] Handle cord-pulled scenarios where we need to refetch payments/refunds on demand to generate receipts

---

sample-app/src/main/java/com/joinforage/android/example/pos/receipts/templates/txs/CashPurchaseTxReceipt.kt
sample-app/src/main/java/com/joinforage/android/example/pos/receipts/templates/txs/CashPurchaseWithCashbackTxReceipt.kt
sample-app/src/main/java/com/joinforage/android/example/pos/receipts/templates/txs/CashWithdrawalTxReceipt.kt
sample-app/src/main/java/com/joinforage/android/example/pos/receipts/templates/txs/SnapPurchaseTxReceipt.kt
sample-app/src/main/java/com/joinforage/android/example/ui/pos/POSComposeApp.kt
sample-app/src/main/java/com/joinforage/android/example/ui/pos/POSViewModel.kt
sample-app/src/main/java/com/joinforage/android/example/ui/pos/screens/payment/PaymentResultScreen.kt
sample-app/src/main/java/com/joinforage/android/example/ui/pos/screens/voids/VoidPaymentResultScreen.kt

Adds support for printing receipts for declined payments. We're essentially cobbling together a manual receipt since we don't really get any receipt data back from the backend when a payment is declined. There is probably be a better way to do this, but this works?
https://linear.app/joinforage/issue/FX-1019/error-handling-need-a-receipt-scene-for-failed-payment-captures
- Manually tested both insufficient funds and incorrect/invalid PIN and saw declined receipts
https://github.com/teamforage/forage-android-sdk/assets/11556475/596c8011-df98-4882-b41c-8b181f7eb257

[FX-1019] Add support for printing receipts for payment declines

---

sample-app/src/main/java/com/joinforage/android/example/ui/pos/POSComposeApp.kt
sample-app/src/main/java/com/joinforage/android/example/ui/pos/POSViewModel.kt

Clears PAN & PIN errors when navigating forward to those screens to avoid showing potentially stale error messages
https://linear.app/joinforage/issue/FX-1047/bug-error-messages-from-previous-entries-persist-across-navigation
- Manually verified in emulator (see demo)
https://github.com/teamforage/forage-android-sdk/assets/11556475/45c7a44b-6cb2-4d17-bf2e-b42c4c2e1c9c

[FX-1047] Fix issue where error messages from previous entries would persist

---

sample-app/src/main/java/com/joinforage/android/example/ui/pos/POSComposeApp.kt
sample-app/src/main/java/com/joinforage/android/example/ui/pos/POSViewModel.kt
sample-app/src/main/java/com/joinforage/android/example/ui/pos/data/PosPaymentResponse.kt
sample-app/src/main/java/com/joinforage/android/example/ui/pos/data/Refund.kt

- Adds `sequence_number` to payment response and refund response ([slack discussion](https://joinforage.slack.com/archives/C06HYPPV2EB/p1707759719149339))
- Updates `messages` refund field to be `message` ([slack discussion](https://joinforage.slack.com/archives/C057H6RGPU0/p1706624389761629))
- Routes `ForageApiResponse.Success` and `ForageApiResponse.Error` responses for payments and refunds to different result screens. This allows us to disambiguate success state with an empty receipt (cord pull or late notification scenario) from a failure state with an empty receipt (declined transaction, invalid pin, etc.)
https://linear.app/joinforage/issue/FX-1074/verify-cord-pulled-scenarios-still-work-with-declined-receipts-code
- Manually verified in the emulator

[FX-1074] Fix cord pull scenarios, update models to reflect server response changes

---

sample-app/src/main/java/com/joinforage/android/example/ui/pos/POSComposeApp.kt
sample-app/src/main/java/com/joinforage/android/example/ui/pos/POSViewModel.kt
sample-app/src/main/java/com/joinforage/android/example/ui/pos/data/PosPaymentResponse.kt

- Improves declined receipts by refetching the payment when a decline fails, which allows us to read the `receipt` field and use that data to populate the declined receipt instead of my cobbled together version.
- Also tidies up the error message to only show the message response instead of the full stringified error
- Updates the terminal ID to read from the receipt's `posTerminal.terminalId` so we're showing the forage ref value
- Updates the logic for PIN errors to only route to a receipt if we have a sequence number, which means we actually tried to capture the payment. 
- For invalid PIN errors like only typing in 3 digits, we never make it to FIS so there's no sequence number, so we won't show a receipt. Instead we'll just show an inline error message. If we _do_ have a sequence …

[FX-1086, FX-1085, FX-1046] Improve declined receipts, fix terminal ID, avoid unknown sequence numbers

---

sample-app/src/main/java/com/joinforage/android/example/ui/pos/POSComposeApp.kt
sample-app/src/main/java/com/joinforage/android/example/ui/pos/POSViewModel.kt

Fixes an issue where we were reading the terminal ID from the wrong place for void receipts.
Also fixes an issue where we were navigating to the receipt view for balance inquiries too early, which meant we weren't displaying the latest data from re-fetching the payment method.
https://linear.app/joinforage/issue/FX-1094/void-receipts-have-the-wrong-terminal-id
Manually verified in the android emulator

[FX-1094] Fix terminal ID on void & balance inquiry receipts 

---

forage-android/src/main/java/com/joinforage/forage/android/ForageSDK.kt
forage-android/src/main/java/com/joinforage/forage/android/pos/ForageTerminalSDK.kt

This PR tweaks three small things, to improve SDK code comments (which will be the eventual docs): 
- Adds a better error code example for functions that tokenize card details 
- Improves error handling description from "troubleshoot" to "unpack" (as requested) 
- Adds `@see` links to the `ForageSDK` comment that match the `ForageTerminalSDK` comment
```
```

[TW-488] Stylistic edits to Android SDK comments

---

forage-android/src/main/java/com/joinforage/forage/android/ForageSDK.kt
forage-android/src/main/java/com/joinforage/forage/android/ForageSDKInterface.kt
forage-android/src/main/java/com/joinforage/forage/android/core/telemetry/Metrics.kt
forage-android/src/main/java/com/joinforage/forage/android/network/data/DeferPaymentRefundRepository.kt
forage-android/src/main/java/com/joinforage/forage/android/pos/ForageTerminalSDK.kt
forage-android/src/main/java/com/joinforage/forage/android/ui/ForagePINEditText.kt
forage-android/src/main/java/com/joinforage/forage/android/vault/AbstractVaultSubmitter.kt
forage-android/src/test/java/com/joinforage/forage/android/mock/MockServerUtils.kt
forage-android/src/test/java/com/joinforage/forage/android/mock/MockServiceFactory.kt
forage-android/src/test/java/com/joinforage/forage/android/pos/ForageTerminalSDKTest.kt

Add the deferred refund endpoint to the Android SDK for Toast to use.
- ✅ I've added unit tests for this change.
Can be released as is.

[FX-1033] Add deferred refund endpoint to terminal SDK

---

forage-android/src/main/java/com/joinforage/forage/android/core/element/state/ElementState.kt
forage-android/src/main/java/com/joinforage/forage/android/network/model/ForageApiResponse.kt

This PR marks several classes as `internal`. 
This hides these classes from the generated docs, reducing developer confusion. 
- ✅ | Unit tests aren't needed for docs and comment changes. 
Check out this branch, and then: 
```
```
Confirm that the classes marked as `internal` do not show up in the generated docs.

[TW-409] Mark private and internal classes

---

sample-app/src/main/java/com/joinforage/android/example/ui/pos/POSComposeApp.kt
sample-app/src/main/java/com/joinforage/android/example/ui/pos/POSViewModel.kt
sample-app/src/main/java/com/joinforage/android/example/ui/pos/data/Merchant.kt
sample-app/src/main/java/com/joinforage/android/example/ui/pos/data/POSUIState.kt
sample-app/src/main/java/com/joinforage/android/example/ui/pos/network/PosApiService.kt
sample-app/src/main/java/com/joinforage/android/example/ui/pos/screens/ActionSelectionScreen.kt
sample-app/src/main/java/com/joinforage/android/example/ui/pos/screens/MerchantSetupScreen.kt

Removes the call to get merchant details from the POS cert app and updates the UI to use a hard-coded test merchant for the merchant name and address. Merchant ID will still read from whatever is provided in the text field in Merchant Setup.
https://linear.app/joinforage/issue/FX-1128/remove-get-merchants-call-from-pos-app
- Manually verified in Android Emulator that expected flows still succeed with mock merchant data using a non-internal token

[FX-1128] Remove get merchants call from pos cert app

---

forage-android/src/main/java/com/joinforage/forage/android/ForageSDKInterface.kt
forage-android/src/main/java/com/joinforage/forage/android/pos/ForageTerminalSDK.kt
forage-android/src/main/java/com/joinforage/forage/android/pos/PosMethodParams.kt
forage-android/src/test/java/com/joinforage/forage/android/pos/ForageTerminalSDKTest.kt

- Move `PosDeferPaymentRefundParams` to the right directory. 
- This ensures POS docs don't pollute the online docs
- Co-locate POS-related imports
⚠️ Technically a breaking change. [Learn more](https://linear.app/joinforage/issue/FX-1161/move-posdeferpaymentrefundparams-to-the-pos-directorymodule)

Move PosDeferPaymentRefundParams to the right module

---

forage-android/src/main/java/com/joinforage/forage/android/core/EnvConfig.kt
forage-android/src/main/java/com/joinforage/forage/android/vault/ForagePinSubmitter.kt
forage-android/src/test/java/com/joinforage/forage/android/core/env/EnvConfigTest.kt

- Changes that should be applied in both this repo and the private fork one.
- The private repo uses more than just `/proxy/` endpoints.

Fixes to facilitate keeping private + public repos in sync

---

forage-android/src/main/java/com/joinforage/forage/android/pos/ForageTerminalSDK.kt
forage-android/src/test/java/com/joinforage/forage/android/pos/ForageTerminalSDKTest.kt
sample-app/src/main/java/com/joinforage/android/example/ui/pos/POSComposeApp.kt
sample-app/src/main/java/com/joinforage/android/example/ui/pos/POSViewModel.kt

ℹ️ The method's implementation is not available publicly, but these changes facilitate keeping the different repositories in sync and **build our public-facing documentation**

Introduce init method in the public repo

---

sample-app/src/main/java/com/joinforage/android/example/ui/pos/POSComposeApp.kt
sample-app/src/main/java/com/joinforage/android/example/ui/pos/POSViewModel.kt
sample-app/src/main/java/com/joinforage/android/example/ui/pos/screens/deferred/DeferredPaymentCaptureResultScreen.kt
sample-app/src/main/java/com/joinforage/android/example/ui/pos/screens/deferred/DeferredPaymentRefundResultScreen.kt
sample-app/src/main/java/com/joinforage/android/example/ui/pos/screens/shared/PinEntryScreen.kt
sample-app/src/main/res/values/strings.xml

- See title
- Deferred actions are the primary (primary Material Design color + shape + position) CTAs, since deferring actions to server is the preferred flow
- Based on #236 since PR 236 includes changes for invoking the `init` method from the sample app, to facilitate keeping the private POS repo in sync
- Manually tried some captures + refunds in the sample app
- Ensured existing non-deferred POS flows still work :)

[FX-1225] Support defer capture + defer refund in POS sample app

---

.idea/kotlinc.xml
.idea/misc.xml
forage-android/src/main/java/com/joinforage/forage/android/network/OkHttpClientBuilder.kt
forage-android/src/main/java/com/joinforage/forage/android/vault/AbstractVaultSubmitter.kt

Add the default version header to all endpoints.
Will test this locally against BT and VGS.

[FX-1184] Add the default header to lock all endpoints

---

forage-android/src/main/java/com/joinforage/forage/android/pos/ForageTerminalSDK.kt

This PR adds the example success schemas to the relevant POS SDK methods. 
Note that I debated including a concrete response instead of the schema, but ultimately I decided to go with the industry standard pattern of the schema. Please Slack me with any questions! 
This could spare customers the trouble of digging in the codebase for the schema. 
- ❌ | Unit tests aren't relevant for comment-only changes. 
- ✅ | ❌ The reviewer should manually test the changes in this PR: 
```
```

[TW-573] Document Android POS SDK example responses

---

forage-android/build.gradle
forage-android/src/main/java/com/joinforage/forage/android/ui/ForageElement.kt
forage-android/src/main/java/com/joinforage/forage/android/ui/ForagePANEditText.kt
forage-android/src/main/java/com/joinforage/forage/android/ui/ForagePINEditText.kt
sample-app/src/main/java/com/joinforage/android/example/ui/complete/flow/balance/FlowBalanceFragment.kt
sample-app/src/main/java/com/joinforage/android/example/ui/complete/flow/tokenize/FlowTokenizeFragment.kt

- Added `showKeyboard` method to `ForageElement` interface
- Implemented `showKeyboard` method in `ForagePANEditText` and `ForagePINEditText`
- Updated `FlowBalanceFragment` and `FlowTokenizeFragment` to use `showKeyboard` method
- To provide a way to show the soft keyboard when needed explicitly
- ❌ I've added unit tests for this change.
- ✅ The reviewer should manually test the changes in this PR.
[Show Keyboard Demo.webm](https://github.com/teamforage/forage-android-sdk/assets/12377418/65f68891-839c-4e34-86ed-ca98c2aa38f5)
~This PR is blocked until we hear back from BT about how to support the show-keyboard functionality with BT inputs. Otherwise the behavior will differ based on the backing vault.~
This PR can now be readily merged 🥳

[FX-1254] Expose `showKeyboard()` method on `ForageElement`s

---

forage-android/src/main/java/com/joinforage/forage/android/core/services/Utils.kt
forage-android/src/main/java/com/joinforage/forage/android/core/services/vault/AbstractVaultSubmitter.kt

Pass Session-Token header through to vault calls
- Send balance check to vgs and bt, confirm that `Session-Token` header is attached as expected

Pass session-token to vault calls

---

forage-android/src/main/java/com/joinforage/forage/android/core/services/launchdarkly/LDManager.kt
forage-android/src/main/java/com/joinforage/forage/android/ecom/ui/ForagePINEditText.kt
forage-android/src/test/java/com/joinforage/forage/android/network/data/LaunchDarklyTest.kt

- Checks `rosetta-traffic-percentage` in LaunchDarkly to determine vault provider, only checking `vault-primary-traffic-percentage` if we aren't using rosetta based on the initial flag check.
- Changes the default third-party vault provider to be BT instead of VGS
- Updates tests to reflect new behavior
https://linear.app/joinforage/issue/FX-1376/fetch-rosetta-traffic-percentage-to-determine-whether-to-route-between
- Added unit tests
Can be merged as-is, as far as I know?

[FX-1376] Fetch rosetta-traffic-percentage to determine vault provider

---

forage-android/src/main/java/com/joinforage/forage/android/core/services/vault/AbstractVaultSubmitter.kt
forage-android/src/main/java/com/joinforage/forage/android/core/ui/VaultWrapper.kt
forage-android/src/main/java/com/joinforage/forage/android/ecom/services/vault/bt/BasisTheoryPinSubmitter.kt
forage-android/src/main/java/com/joinforage/forage/android/ecom/services/vault/vgs/VgsPinSubmitter.kt
forage-android/src/main/java/com/joinforage/forage/android/ecom/ui/ForagePINEditText.kt
forage-android/src/main/java/com/joinforage/forage/android/ecom/ui/vault/bt/BTVaultWrapper.kt
forage-android/src/main/java/com/joinforage/forage/android/ecom/ui/vault/vgs/VGSVaultWrapper.kt

Introduce `SecurePinCollector` interface for passing backing-vault facilities to pin-submitter logic
All of the pin submitter facilities are coupled to `ForagePINEditText`. That wasn't an issue before, but now we need the flexibility of passing non-EditText-based UI components to pin submitters to support the `ForagePinPad` in the Pos SDK.
- ❌ I did not add tests since these are view-layer changes with no logic branches
- ❌ No need to manually review as passing CI tests are sufficient
N/A since this just changes implementation details
This can be merged in once #254 is merged.

[FX-1383] Use `SecurePinCollector` to decouple PinSubmitters from `ForagePINEditText`

---

forage-android/src/main/java/com/joinforage/forage/android/core/services/forageapi/network/OkHttpClientBuilder.kt

We need the ability to modify the several request headers on
a per request basis using an `OkHttpClient` instance.
The previous usage of `OkHttpClient().newBuilder()` had the
effect of creating a new `OkHttpClient` instance with distinct
thread and connection pool resources for each `OkHttpClient`
instance created. This caused some concern about excessive
resource consumption.
Originally, we were considering shutting down each
`okHttpClient` instance manually after using it. However,
there were thread complications because shutting down an
`okHttpClient` requires dispatching a separate thread but
we also do some view manipulation when we clear the PIN
field and Android doesn't allow view manipulation across
threads.
But then, after further examining [the OkHttpClient …

[FX-1462] Use shared OkHttpClient instance

---

forage-android/src/main/res/values/attrs.xml

Adds missing types to `<attr />`s on the `ForagePINEditText`'s `<declare-styleable>.
Overcommunicate to SDK users the intended type of these `<attr />`.
- ❌ Manual testing is unnecessary since these changes do not affect runtime; they are largely just for documentation. 
N/A These changes don't have an affect on runtime so nothing to demo
Can be rolled out immediately

[FX-1463] Add types to `ForagePINEditText` custom styles

---

forage-android/src/main/java/com/joinforage/forage/android/core/ui/element/ForageElement.kt

Move EditText-specific methods out of `ForageElment` interface and into `EditTextElement` interface.
Leaving these methods on the `ForageElement` would force the Pos SDK's non-EditText-based UI components to implement these methods, which makes no sense. Methods that make sense for EditText UI components should live on the EditText-specific interface and not on the base ForageElement interface that even non-EditText UI components implement.
- ❌ No unit tests are necessary here
- ❌ Nothing runtime-related changed manually testing is unnecessary. 
N/A as this is just implementation
Can be merged after #265 is merged

[FX-1459] Move EditText methods to `EditTextElement` interface

---

forage-android/src/main/java/com/joinforage/forage/android/ecom/services/ForageSDK.kt
forage-android/src/main/java/com/joinforage/forage/android/ecom/ui/element/ForagePANEditText.kt
forage-android/src/main/java/com/joinforage/forage/android/ecom/ui/element/ForagePINEditText.kt
forage-android/src/test/java/com/joinforage/forage/android/mock/MockServiceFactory.kt
forage-android/src/test/java/com/joinforage/forage/android/network/data/CapturePaymentRepositoryTest.kt
forage-android/src/test/java/com/joinforage/forage/android/network/data/CheckBalanceRepositoryTest.kt
forage-android/src/test/java/com/joinforage/forage/android/network/data/DeferPaymentCaptureRepositoryTest.kt
sample-app/src/main/java/com/joinforage/android/example/ui/complete/flow/balance/FlowBalanceFragment.kt
sample-app/src/main/java/com/joinforage/android/example/ui/complete/flow/balance/FlowBalanceViewModel.kt
sample-app/src/main/java/com/joinforage/android/example/ui/complete/flow/payment/capture/FlowCapturePaymentViewModel.kt
sample-app/src/main/java/com/joinforage/android/example/ui/complete/flow/tokenize/FlowTokenizeFragment.kt
sample-app/src/main/java/com/joinforage/android/example/ui/complete/flow/tokenize/FlowTokenizeViewModel.kt
sample-app/src/main/res/layout/fragment_catalog.xml
sample-app/src/main/res/layout/fragment_flow_balance.xml
sample-app/src/main/res/layout/fragment_flow_capture_payment.xml
sample-app/src/main/res/layout/fragment_flow_tokenize.xml
sample-app/src/main/res/layout/fragment_ui_components_pan.xml
sample-app/src/main/res/layout/fragment_ui_components_pin.xml

Moves both `ForagePANEditText` and `ForagePINEditText`:
* from `ecom.ui.`
* to `ecom.ui.element`
Keeps the semantics of the package structure sensical ("Elements live in `.elements`") and aligned with `.core`. Since these elements are public surface area, it is better to re-home them in a future-looking way now since it's a breaking change to do it later
- ❌ No but the test suite has been updated to reflect the new paths. 
- ❌ No need to manually review with the CI tests passing. 
N/A as it's just an implementation change
Can be merged after #267

[1461] Move `Forage*EditText`s to `ecom.ui.element`

---

forage-android/src/main/java/com/joinforage/forage/android/core/services/EnvConfig.kt
forage-android/src/main/java/com/joinforage/forage/android/core/services/ForageConfig.kt
forage-android/src/main/java/com/joinforage/forage/android/core/services/telemetry/Log.kt
forage-android/src/main/java/com/joinforage/forage/android/core/ui/element/ForageConfigManager.kt
forage-android/src/main/java/com/joinforage/forage/android/core/ui/element/ForageElement.kt
forage-android/src/main/java/com/joinforage/forage/android/core/ui/element/ForagePanElement.kt
forage-android/src/main/java/com/joinforage/forage/android/ecom/services/ForageSDK.kt
forage-android/src/main/java/com/joinforage/forage/android/ecom/ui/element/ForagePINEditText.kt
forage-android/src/test/java/com/joinforage/forage/android/core/env/EnvConfigTest.kt
forage-android/src/test/java/com/joinforage/forage/android/mock/MockLogger.kt
forage-android/src/test/java/com/joinforage/forage/android/ui/ForageConfigManagerTest.kt
sample-app/src/main/java/com/joinforage/android/example/ui/catalog/CatalogFragment.kt
sample-app/src/main/java/com/joinforage/android/example/ui/complete/flow/balance/FlowBalanceFragment.kt
sample-app/src/main/java/com/joinforage/android/example/ui/complete/flow/payment/capture/FlowCapturePaymentFragment.kt
sample-app/src/main/java/com/joinforage/android/example/ui/complete/flow/tokenize/FlowTokenizeFragment.kt

Moves `ForageConfig`:
* from: `core.ui.element.ForageConfig`
* to: `core.services.ForageConfig`
`ForageConfig`,  while consumed by UI components, is a standalone data structure making the `core.services` package a more appropriate home. This also aligns with the Pos SDK because the `ForageTerminalSDK`, a service, also consumes the `ForageConfig`. The philosophy here is:
_UI may depend on services but services should never depend on UI else those services ought to live in the`.ui` package!!_
- ✅ Test suites have been updated to reflect the new `ForageConfig` home.
- ❌ There is no need to manually test these changes with passing CI. 
N/A just changes implementation details
Can be rolled out after #262

Move ForageConfig to core.services

---

forage-android/src/main/java/com/joinforage/forage/android/core/ui/element/ForagePinElement.kt
forage-android/src/main/java/com/joinforage/forage/android/ecom/ui/vault/bt/BTVaultWrapper.kt
forage-android/src/main/res/values/attrs.xml
sample-app/src/main/java/com/joinforage/android/example/ui/complete/flow/balance/FlowBalanceFragment.kt
sample-app/src/main/res/values/styles.xml

- https://joinforage.slack.com/archives/C056QGRF6S3/p1712687133981029?thread_ts=1712680102.191409&cid=C056QGRF6S3
- ✅ See demo below
- ✅  Can still call `setHint` and `setHintTextColor` (no code change needed), but it will be no-op and show a warning message.
Successor of https://github.com/teamforage/forage-android-sdk/pull/244

[FX-1508] Deprecate PIN hint and hint color customization

---

forage-android/src/main/java/com/joinforage/forage/android/core/services/ForageConfig.kt
forage-android/src/main/java/com/joinforage/forage/android/core/services/ForageConfigNotSetException.kt
forage-android/src/main/java/com/joinforage/forage/android/core/ui/element/ElementValidationErrors.kt
forage-android/src/main/java/com/joinforage/forage/android/core/ui/element/ForageElement.kt
forage-android/src/main/java/com/joinforage/forage/android/core/ui/element/ForagePanElement.kt
forage-android/src/main/java/com/joinforage/forage/android/core/ui/element/ForagePinElement.kt
forage-android/src/main/java/com/joinforage/forage/android/core/ui/element/ForageVaultElement.kt
forage-android/src/main/java/com/joinforage/forage/android/core/ui/element/state/EditTextState.kt
forage-android/src/main/java/com/joinforage/forage/android/core/ui/element/state/ElementState.kt
forage-android/src/main/java/com/joinforage/forage/android/core/ui/element/state/pan/PanEditTextState.kt
forage-android/src/main/java/com/joinforage/forage/android/core/ui/element/state/pan/StrictEbtValidator.kt
forage-android/src/main/java/com/joinforage/forage/android/core/ui/element/state/pin/PinEditTextState.kt
forage-android/src/main/java/com/joinforage/forage/android/ecom/services/ForageSDK.kt
forage-android/src/main/java/com/joinforage/forage/android/ecom/services/vault/bt/BTResponseParser.kt
forage-android/src/main/java/com/joinforage/forage/android/ecom/services/vault/bt/BaseResponseRegExp.kt
forage-android/src/main/java/com/joinforage/forage/android/ecom/services/vault/forage/RosettaResponseParser.kt
forage-android/src/main/java/com/joinforage/forage/android/ecom/services/vault/vgs/VGSResponseParser.kt
forage-android/src/main/java/com/joinforage/forage/android/ecom/ui/element/ForagePANEditText.kt
forage-android/src/main/java/com/joinforage/forage/android/ecom/ui/element/ForagePINEditText.kt
forage-android/src/test/java/com/joinforage/forage/android/core/element/state/pan/PanInputStateTest.kt

- left comments throughout the PR to facilitate the review
Here are some changes:
- ⚠️ @devinmorgan Removed deprecated `TooLongEbtPanError`, was previously marked as "Deprecated"
- ⚠️ @devinmorgan Use `foragePanEditText: ForagePANEditText` instead of `foragePanEditText: ForagePanElement`
- Made internal-only vault parsing logic internal
- Fixed KDoc [references/links](https://kotlinlang.org/docs/kotlin-doc.html#links-to-elements)
- **USE only *core* KDoc references** (no ecom or POS references)
- e.g. `[ForageElement][com.joinforage....ecom...]` inside a core file is not allowed! 
- removed POS-specific Kdoc comments
- To prepare v4.0.0 release and updated docs!
- ✅ Ran Dokka locally!
Can be released as-is! 
**I'll manually publish the updated SDK reference docs before 6/20**

[FX-1514] v4.0.0 final touches - fix Kdoc comments and make internal code internal

---

forage-android/src/main/java/com/joinforage/forage/android/ecom/ui/element/ForagePINEditText.kt
forage-android/src/main/java/com/joinforage/forage/android/ecom/ui/vault/forage/RosettaPinElement.kt
sample-app/src/main/java/com/joinforage/android/example/ui/catalog/CatalogFragment.kt
sample-app/src/main/res/layout/fragment_catalog.xml

Fix PIN field sizing discrepancies between BT and Rosetta for xml-initialized and dynamically-initialized `ForagePINEditText`.
This PR also simplifies the **catalog** view of the Sample App since the previous view was overwhelming to develop against. 
The previous fix only:
1. zero'd out padding when the ForagePINEditText was rendered via XML; it did not zero out padding for dynamically rendered ForagePINEditText
2. did not address the styling discrepancies between BT and rosetta due different default textSizes
See [this code comment](https://app.graphite.dev/github/pr/teamforage/forage-android-sdk/277/Add-dynamically-created-ForagePINEditText-to-catalog#comment-PRRC_kwDOIQqcBs5iOMav) for more details.
- ❌ No unit tests for this since it's styling
- ✅ Danilo and Devin have both …

Fix PIN Styling Parity for XML and dynamic rendering

---

forage-android/src/main/java/com/joinforage/forage/android/ecom/ui/vault/forage/RosettaPinElement.kt
sample-app/src/main/java/com/joinforage/android/example/ui/catalog/CatalogFragment.kt
sample-app/src/main/res/layout/fragment_catalog.xml
sample-app/src/main/res/values/attrs.xml
sample-app/src/main/res/values/styles.xml
sample-app/src/main/res/values/themes.xml

Modifies `RosettaPinElement` to support styling via `@style/...`. This PR also updates the Catalog view of the the Sample App so that the xml-rendered `ForagePINEditText` and the dynamically created `ForagPINEditText` point to the same style.
Previously, the `RosettaPinElement` could not be styled this way, which made it cumbersome to style dynamically created `ForagePINEditTexts`. 
- ❌ No new tests since this is just styling changes
- ✅ By the time this PR get's merged in, both Devin and Danilo will have manually tested this extensively.
In the dynamically rendered `ForagePINEditText`, the `RosettaPinElement` does not show the intended style.
Now both `RosettaPinElement` and BT's `TextElement` show the desired styles for the xml-rendered and dynamically-rendered `ForagePINEditText`s
Can …

Support `@styles/...` on `RosettaPinElement`

---

forage-android/src/main/java/com/joinforage/forage/android/ecom/ui/element/ForagePINEditText.kt
forage-android/src/main/java/com/joinforage/forage/android/ecom/ui/vault/rosetta/RosettaPinElement.kt
forage-android/src/test/java/com/joinforage/forage/android/ui/RosettaPinElementTests.kt

Rename ecom/ui/vault/forage -> ecom/ui/vault/rosetta
All of the moving parts use the prefix rosetta instead of forage. For example:
* `RosettaPinElement`
* `RosettaPinSubmitter`
etc.
Also, calling an implementation detail "forage" is unproductive because all the implementation details are forage-relate
- ✅ Updated unit tests 
- ❌ Passing CI tests and unit tests is sufficient
N/A this is an implementation detail
I've marked this PR to merge when ready

Rename ecom/ui/vault/forage -> ecom/ui/vault/rosetta

---

forage-android/src/main/java/com/joinforage/forage/android/core/services/forageapi/polling/PollingService.kt
forage-android/src/main/java/com/joinforage/forage/android/ecom/services/launchdarkly/LDManager.kt
forage-android/src/main/java/com/joinforage/forage/android/ecom/ui/element/ForagePINEditText.kt
forage-android/src/test/java/com/joinforage/forage/android/network/data/LaunchDarklyTest.kt

* Moves `LDManager` and related LaunchDarkly functionality from the core services to the Ecom services.
Only the Ecom repo uses LD. To reflect this truth, the LD service needs to live in `/ecom` instead of `/core` 
- ✅ Unit tests have been updated
- ❌ Passing CI tests and unit tests are sufficient
N/A just implementation details
I've marked this PR to merge when ready

Move LD facilities into /ecom

---

forage-android/src/main/java/com/joinforage/forage/android/core/ui/textwatcher/PinTextWatcher.kt
forage-android/src/main/java/com/joinforage/forage/android/ecom/ui/vault/rosetta/RosettaPinElement.kt
forage-android/src/test/java/com/joinforage/forage/android/ui/PinTextWatcherTest.kt

Drop `PinTextWatcher` 's internal `EditText` field and just use passed `editable` argument instead
Reduce implementation complexity
- ✅ I've updated the appropriate unit tests
- ❌ CI tests and unit tests are sufficient
N/A it's just implementation details
I've marked this PR to merge when ready

Simplify PinTextWatcher

---

forage-android/src/main/java/com/joinforage/forage/android/core/services/telemetry/Log.kt
forage-android/src/main/java/com/joinforage/forage/android/ecom/services/ForageSDK.kt
forage-android/src/test/java/com/joinforage/forage/android/mock/MockLogger.kt

1. Each `Log` method now returns the current instance (`this`).
2. Updated implementations of `Log` interface to reflect this change.
This change allows for a fluent interface when using the `Log` methods, making the logging implementation more expressive and chaining multiple log actions in a more concise way.
- ✅ Existing unit tests have been updated
- ❌ Passing CI and unit tests are sufficient 
N/A implementation detail
I've marked this PR to merge once eligibility

Support method chaining in forage Logger

---

forage-android/src/main/java/com/joinforage/forage/android/core/services/telemetry/Metrics.kt
forage-android/src/main/java/com/joinforage/forage/android/core/services/vault/AbstractVaultSubmitter.kt
forage-android/src/main/java/com/joinforage/forage/android/ecom/services/ForageSDK.kt
forage-android/src/test/java/com/joinforage/forage/android/core/telemetry/metrics/ResponseMonitorTest.kt

This pull request refactors the telemetry metrics logic in the Forage Android SDK. The key changes include:
- Removed redundant `start` and `end` methods from `PerformanceMeasurer` and `NetworkMonitor` interfaces.
- Support method chaining in abstract `ResponseMonitor` class  (via generics)
- Drop unnecessary factory methods and interfaces from `VaultProxyResponseMonitor` and `CustomerPerceivedResponseMonitor`.
- Move `processApiResponseForMetrics` logic from `ForageSDK` to `Metrics`
Reduce implementation and usage complexity, improve maintainability, and enhance the flexibility.
- ✅ I've updated unit tests for this change. 
- ❌ Passing CI tests and unit tests is sufficient
N/A just implementation details
I've marked this PR to merge when ready

Reduce verbosity of Metrics facilities

---

forage-android/src/main/java/com/joinforage/forage/android/core/ui/element/ForagePinElement.kt
forage-android/src/main/java/com/joinforage/forage/android/ecom/services/ForageSDK.kt
forage-android/src/main/java/com/joinforage/forage/android/ecom/ui/element/ForagePINEditText.kt

Move `getVaultSubmitter()` and `showKeyboard()` methods from `ForagePINEditText` to parent `ForagePinElement` class.
These methods do not care about the specific vault or details that `ForagePINEditText` would specify in Pos or Ecom land. Moving these methods to the parent is a small reducing code duplication / maintenance burden win
CI tests pass
N/A
Can be rolled out immediately

Move two methods up one level in class hierarchy

---

forage-android/src/main/java/com/joinforage/forage/android/ecom/services/ForageSDK.kt
forage-android/src/test/java/com/joinforage/forage/android/network/EncryptionKeyServiceTest.kt
forage-android/src/test/java/com/joinforage/forage/android/network/TokenizeCardServiceTest.kt
forage-android/src/test/java/com/joinforage/forage/android/network/data/CapturePaymentRepositoryTest.kt
forage-android/src/test/java/com/joinforage/forage/android/network/data/CheckBalanceRepositoryTest.kt
forage-android/src/test/java/com/joinforage/forage/android/network/data/DeferPaymentCaptureRepositoryTest.kt
forage-android/src/test/java/com/joinforage/forage/android/vault/BasisTheoryPinSubmitterTest.kt
forage-android/src/test/java/com/joinforage/forage/android/vault/RosettaPinSubmitterTest.kt
sample-app/src/main/java/com/joinforage/android/example/ui/complete/flow/balance/FlowBalanceViewModel.kt
sample-app/src/main/java/com/joinforage/android/example/ui/complete/flow/payment/capture/FlowCapturePaymentViewModel.kt
sample-app/src/main/java/com/joinforage/android/example/ui/complete/flow/tokenize/FlowTokenizeViewModel.kt

We got single-error objects for free from the work in #290. This PR applies that benefit to the rest of our codebase 
`.error` is less verbose than `.errors[0]`. It also allows the compiler to make stronger type safety guarantees. Before, the compiler would require merchants to handle cases where `.errors[0]` could be thrown or otherwise did not exist. This gets the Android SDK to parity with the iOS and JS SDKs
- ✅ I've modified unit tests for this change. 
- ❌ No need to manually test the changes in this PR because the automated and CI tests pass. 
Check out the code changes in the sample app files!
Must be rolled out after #290, but it's planned to be released after the #289

Update sdk + sample app to use single error

---

forage-android/src/main/java/com/joinforage/forage/android/core/services/ForageConfig.kt
forage-android/src/main/java/com/joinforage/forage/android/core/ui/element/ForageElement.kt
forage-android/src/main/java/com/joinforage/forage/android/core/ui/element/ForagePanElement.kt
forage-android/src/main/java/com/joinforage/forage/android/ecom/services/ForageSDK.kt
forage-android/src/main/java/com/joinforage/forage/android/ecom/ui/element/ForagePINEditText.kt

This PR updates the `merchantId` description and code snippets to reflect the new best practices after PAID-1227 (to no longer use `mid/`).

[TW-700] Remove mid/ from Android online-only SDK docs 

---

forage-android/src/main/java/com/joinforage/forage/android/core/ui/element/state/pan/PanInputState.kt
forage-android/src/main/java/com/joinforage/forage/android/core/ui/element/state/pan/StateIIN.kt
forage-android/src/main/java/com/joinforage/forage/android/core/ui/textwatcher/FormatPanTextWatcher.kt
forage-android/src/test/java/com/joinforage/forage/android/core/element/state/pan/PanInputStateTest.kt

Added support for Maine's 16-digit and 19-digit PAN numbers by updating the state IIN validation logic to handle multiple valid PAN lengths for a single state.
Maine issues EBT cards with both 16 and 19-digit PAN numbers, but our system previously only supported 19-digit PANs. This change ensures we can properly validate and format both PAN lengths.
- ✅ Added comprehensive unit tests for both 16 and 19-digit Maine PAN validation
- ✅  Manual testing not required as this is covered by unit tests
Here's a visual of `ForagePANEditText` playing nicely with Maine's (BIN `507703`) 16 and 19 digit PANs
<div class='graphite__hidden'>
<div>🎥 Video uploaded on Graphite:</div>
<a href="https://app.graphite.dev/media/video/IfyQmT9sZxXL1kIgYI4y/4a5a9f8d-de6b-4faf-adb6-f4a7317d64c5.webm">
</a>
</div> …

Support 16 and 19 Digit Maine PANs

---

README.md
forage-android/build.gradle

Bump SDK version to 4.2.0 
We're calling the Maine PAN fix a MINOR not a PATCH
Simple version update that can be reverted if needed.

Bump to 4.2.0

---

.github/workflows/CI.yaml

https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/

Fix the deprecated upload-artifact@v3 package

---

forage-android/build.gradle
sample-app/build.gradle

[INSTORE-34: \[Online SDK\]\[Security\] \[CVE-2023-0833\] Okhttp Information Exposure Vulnerability](https://linear.app/joinforage/issue/INSTORE-34/online-sdksecurity-cve-2023-0833-okhttp-information-exposure)
CI tests pass and I tested locally and confirmed logs work
Can be rolled out immediately

[INSTORE-28]Address Okhttp Information Exposure Vulnerability

---

sample-app/src/main/java/com/joinforage/android/example/ui/complete/flow/tokenize/FlowTokenizePaymentSheetFragment.kt

Hide soft keyboard on submit in sample-app.
So mobile QA tests can find the element with the result.
Mobile QA tests

[EXPA-265] Hide soft keyboard on submit in sample-app
