- .github/workflows/Lint.yaml
- forage-android/build.gradle
This PR will setup Android Lint and will run on PRs
> Add Lint job

- build.gradle
- forage-android/build.gradle
- sample-app/build.gradle
- sample-app/src/main/java/com/joinforage/android/example/network/di/ForageApiModule.kt
Removes Moshi reflection from the sample app
- Bumps Kotlin to 1.7.21
> Remove Moshi reflection in the sample app

- forage-android/build.gradle
- forage-android/src/main/java/com/joinforage/forage/android/network/ForageConstants.kt
- forage-android/src/main/java/com/joinforage/forage/android/network/OkHttpClientBuilder.kt
- forage-android/src/main/java/com/joinforage/forage/android/network/TokenizeCardService.kt
- forage-android/src/main/java/com/joinforage/forage/android/network/model/ForageApiResponse.kt
- forage-android/src/test/java/com/joinforage/forage/android/fixtures/CreatePaymentMethodFixtures.kt
- forage-android/src/test/java/com/joinforage/forage/android/network/TokenizeCardServiceTest.kt
This PR creates TokenizeCardService, and its tests
> Cherry-pick TokenizeCardService

- README.md
- build.gradle
- forage-android/build.gradle
Adding [Kover](https://github.com/Kotlin/kotlinx-kover) to extract code coverage
> Generate code coverage report using Kover

- forage-android/src/main/java/com/joinforage/forage/android/network/EncryptionKeyService.kt
- forage-android/src/test/java/com/joinforage/forage/android/fixtures/EncryptionKeyFixtures.kt
- forage-android/src/test/java/com/joinforage/forage/android/model/encryption/ErrorResponse.kt
- forage-android/src/test/java/com/joinforage/forage/android/network/EncryptionKeyServiceTest.kt
- forage-android/src/test/resources/fixtures/encryption/key/successful_get_encryption_key.json
- forage-android/src/test/resources/fixtures/encryption/key/unauthorized_get_encryption_key.json
This PR creates `EncryptionKeyService`, and its tests
> Cherry-pick EncryptionKeyService

- forage-android/src/main/java/com/joinforage/forage/android/collect/PinCollector.kt
- forage-android/src/main/java/com/joinforage/forage/android/collect/VGSPinCollector.kt
This PR creates the `PinCollector` interface to isolate VGS implementation
> Add PinCollector interface

- README.md
- forage-android/build.gradle
- forage-android/src/main/java/com/joinforage/forage/android/ForageSDK.kt
- forage-android/src/main/java/com/joinforage/forage/android/ForageSDKApi.kt
- sample-app/src/main/java/com/joinforage/android/example/ui/complete/flow/tokenize/FlowTokenizeViewModel.kt
Using [kotlinx.coroutines](https://github.com/Kotlin/kotlinx.coroutines) we can transform all the callbacks into suspending functions.
> Make tokenizeEBTCard a suspending function

- sample-app/src/main/java/com/joinforage/android/example/network/interceptors/AuthInterceptor.kt
- sample-app/src/main/java/com/joinforage/android/example/ui/complete/flow/tokens/model/TokensUIDefaultState.kt
Adding the dev token and merchant account
> Add dev token and merchant account

- README.md
- forage-android/src/main/java/com/joinforage/forage/android/collect/VGSPinCollector.kt
- forage-android/src/main/java/com/joinforage/forage/android/model/Balance.kt
- forage-android/src/main/java/com/joinforage/forage/android/model/Card.kt
- forage-android/src/main/java/com/joinforage/forage/android/model/PanEntry.kt
- forage-android/src/main/java/com/joinforage/forage/android/model/StateIIN.kt
- forage-android/src/main/java/com/joinforage/forage/android/network/mapper/ToResponse.kt
- forage-android/src/main/java/com/joinforage/forage/android/network/model/PaymentMethod.kt
- forage-android/src/main/java/com/joinforage/forage/android/network/model/PaymentMethodRequestBody.kt
- forage-android/src/main/java/com/joinforage/forage/android/network/model/Response.kt
- Adding internal modifier to all SDK classes
- Adding steps to run unit tests on README
> Add internal modifier and update README

- sample-app/src/main/java/com/joinforage/android/example/ui/complete/flow/payment/capture/FlowCapturePaymentViewModel.kt
Add more logs to the sample app
> Add logs to FlowCapturePaymentViewModel

- README.md
- forage-android/src/main/java/com/joinforage/forage/android/ForageSDK.kt
- forage-android/src/main/java/com/joinforage/forage/android/ForageSDKApi.kt
- forage-android/src/main/java/com/joinforage/forage/android/network/ForageConstants.kt
- forage-android/src/main/java/com/joinforage/forage/android/ui/ForagePANEditText.kt
- forage-android/src/main/java/com/joinforage/forage/android/ui/ForagePINEditText.kt
- forage-android/src/main/java/com/joinforage/forage/android/ui/LogoImageView.kt
Use PIN_FIELD_NAME constant inside `ForagePINEditText` and update readme
> Use PIN_FIELD_NAME constant and update readme

- forage-android/src/test/java/com/joinforage/forage/android/fixtures/CreatePaymentMethodFixtures.kt
- forage-android/src/test/java/com/joinforage/forage/android/fixtures/GetMessageFixtures.kt
- forage-android/src/test/java/com/joinforage/forage/android/network/MessageStatusServiceTest.kt
- forage-android/src/test/java/com/joinforage/forage/android/network/TokenizeCardServiceTest.kt
- forage-android/src/test/java/com/joinforage/forage/android/network/data/CapturePaymentRepositoryTest.kt
- forage-android/src/test/java/com/joinforage/forage/android/network/data/CheckBalanceRepositoryTest.kt
- forage-android/src/test/resources/fixtures/payment/methods/failed_create_payment_method.json
- forage-android/src/test/resources/fixtures/payment/methods/successful_create_payment_method.json
- forage-android/src/test/resources/fixtures/payment/methods/successful_create_payment_method_message.json
I bolstered the current test suite to increase code coverage and bring this repository up to speed with our other products.
Yes
> Improve unit test coverage

- forage-android/src/main/java/com/joinforage/forage/android/collect/VGSPinCollector.kt
Once the submit function is called for the PIN, remove the saved PIN from the input field.
https://user-images.githubusercontent.com/89605898/232502378-fc545292-8df6-4e06-9384-11154c839b68.mp4
> Reset pin field once it is submitted

- README.md
- forage-android/src/main/java/com/joinforage/forage/android/ForageSDK.kt
- forage-android/src/main/java/com/joinforage/forage/android/ForageSDKApi.kt
- forage-android/src/main/java/com/joinforage/forage/android/network/TokenizeCardService.kt
- forage-android/src/main/java/com/joinforage/forage/android/network/model/PaymentMethod.kt
- forage-android/src/main/java/com/joinforage/forage/android/network/model/PaymentMethodRequestBody.kt
- forage-android/src/test/java/com/joinforage/forage/android/fixtures/CreatePaymentMethodFixtures.kt
- forage-android/src/test/java/com/joinforage/forage/android/network/TokenizeCardServiceTest.kt
- forage-android/src/test/resources/fixtures/payment/methods/successful_create_payment_method.json
- sample-app/src/main/java/com/joinforage/android/example/data/PaymentsRepository.kt
- sample-app/src/main/java/com/joinforage/android/example/network/model/PaymentRequest.kt
- sample-app/src/main/java/com/joinforage/android/example/ui/complete/flow/tokenize/FlowTokenizeFragment.kt
- sample-app/src/main/java/com/joinforage/android/example/ui/complete/flow/tokenize/FlowTokenizeViewModel.kt
- sample-app/src/main/res/layout/fragment_flow_tokenize.xml
- sample-app/src/main/res/navigation/mobile_navigation.xml
- Refactor `userID` -> `customerID`
- Refactor `user_id` -> `customer_id`
- Refactor `<x>UserID` -> `<x>CustomerID`
- Refactor `user id` -> `customer id`
- Refactor `user-id` -> `customer-id`
- [Update snippet to use test UUID value](https://github.com/teamforage/forage-android-sdk/pull/32/commits/4289e9757d44ebff7bd41cf4a6f333bd06942950)
https://linear.app/joinforage/issue/FOR-2012/refactor-userid-customerid-in-forage-android-sdk
- Tests use customerId instead of userId now
> [FOR-2012] Refactor userId -> customerId

- forage-android/src/main/java/com/joinforage/forage/android/network/PaymentMethodService.kt
- forage-android/src/main/java/com/joinforage/forage/android/network/PaymentService.kt
- forage-android/src/main/java/com/joinforage/forage/android/network/TokenizeCardService.kt
- sample-app/src/main/java/com/joinforage/android/example/network/ForageApi.kt
☝️ 
- Ticket: [COR-36](https://linear.app/joinforage/issue/COR-36/update-the-version-name-across-the-board-to-reflect-the-api-release)
- ❌ Not a front-end change
- ❌ Android QA Tests passed locally
- ❌ Unit Tests passed locally
> [COR-36] Update to actual customer ID release version name

- README.md
This PR adds parameter definitions. It also includes some minor edits like adding in headers and changing future tense to present. 
Please let me know of any questions or of things that you'd like me to change. Thank you!
> [TW-189] Doc updates

- forage-android/src/main/java/com/joinforage/forage/android/core/element/ElementValidationErrors.kt
- forage-android/src/main/java/com/joinforage/forage/android/core/element/state/PanElementStateManager.kt
- forage-android/src/main/java/com/joinforage/forage/android/model/StateIIN.kt
- forage-android/src/test/java/com/joinforage/forage/android/core/element/state/PanElementStateManagerTest.kt
Please include a summary of the change. Please also include relevant motivation and context. List any dependencies that are required for this change.
- Add any other relevant change made on this PR.
- Describe your changes
- YES or NO. If not, why?
> Enrich PAN-validation with State IIN logic

- forage-android/src/main/java/com/joinforage/forage/android/ui/ForagePANEditText.kt
[Gopuff flagged that the focus and blur events were not firing
correctly](https://joinforage.slack.com/archives/C04FQM5F2DA/p1691443021122609) when they set end-icon-mode to `clear_text`. Really
really really bizarre bug. Regretfully, I still don't know with
certainty what the underlying issue was. For now, the fix seems
to be attaching the event listener after the view has been added
- YES or NO. If not, why?
I tried to setup [Espresso tests](https://developer.android.com/training/testing/espresso) for this but it was taking longer than I could afford and wrote that off as out-of-scope given the urgency of fixing this but
A video of the `focus`, `blur`, and `change` events firing when the `TextInputLayout` has end-icon-clear-text, which is the setup that was causing GoPuff issues …
> Fix focus/blur event handler not firing bug

- forage-android/src/main/java/com/joinforage/forage/android/core/element/state/PanElementStateManager.kt
- forage-android/src/main/java/com/joinforage/forage/android/model/StateIIN.kt
- forage-android/src/test/java/com/joinforage/forage/android/core/element/state/PanElementStateManagerTest.kt
This is a separate PR to address [Danilo's comment](https://github.com/teamforage/forage-android-sdk/pull/67#pullrequestreview-1584909233) on #67 
- YES - updates the relevant test
No screenshots since the tests confirm it
> Update isValid to be true for less than 6 digits

- forage-android/build.gradle
- gradle.properties
Igor flagged [the latest version 2.0.4](https://joinforage.slack.com/archives/C04FQM5F2DA/p1692715902020199?thread_ts=1692710386.153339&cid=C04FQM5F2DA) was broken
> Go back to hardcoding the release version for now

- forage-android/build.gradle
- gradle.properties
Please include a summary of the change. Please also include relevant motivation and context. List any dependencies that are required for this change.
- Add any other relevant change made on this PR.
- Describe your changes
- YES or NO. If not, why?
> Bump version to 2.0.5 for release

- sample-app/src/main/java/com/joinforage/android/example/ui/complete/flow/balance/FlowBalanceFragment.kt
- sample-app/src/main/java/com/joinforage/android/example/ui/complete/flow/tokenize/FlowTokenizeFragment.kt
- sample-app/src/main/res/layout/fragment_flow_balance.xml
- sample-app/src/main/res/layout/fragment_flow_tokenize.xml
Adjust the sample app so that the qa-tests can more easily validate state.
> [FX-498] Display element state on screen for qa-tests

- CONTRIBUTING.md
- docs/pull_request_template.md
- Update PR template
- Rename + format markdown in CONTRIBUTING.md
- Renamed CONTRIBUTING.md for improved discoverability.
- Use Markdown comments where applicable; promotes and reduces time to write easy-to-digest PR descriptions
- Foster a culture of dogfooding; Make it easier for reviewers to manually test changes locally
- Add rollout plan section
- Include section for screenshots and screen recordings
Changes only markdown
- ❌ The reviewer should manually test the changes in this PR. 
N/A
Can  be released as-is.
> [FX-504] Update PR template

- forage-android/build.gradle
- gradle.properties
> Bumpt to version 2.0.8

- forage-android/src/main/java/com/joinforage/forage/android/ForageSDK.kt
- forage-android/src/main/java/com/joinforage/forage/android/collect/BTPinCollector.kt
- forage-android/src/main/java/com/joinforage/forage/android/collect/VGSPinCollector.kt
- forage-android/src/main/java/com/joinforage/forage/android/core/Log.kt
- forage-android/src/main/java/com/joinforage/forage/android/network/EncryptionKeyService.kt
- forage-android/src/main/java/com/joinforage/forage/android/network/ForageConstants.kt
- forage-android/src/main/java/com/joinforage/forage/android/network/MessageStatusService.kt
- forage-android/src/main/java/com/joinforage/forage/android/network/NetworkService.kt
- forage-android/src/main/java/com/joinforage/forage/android/network/OkHttpClientBuilder.kt
- forage-android/src/main/java/com/joinforage/forage/android/network/PaymentMethodService.kt
- forage-android/src/main/java/com/joinforage/forage/android/network/PaymentService.kt
- forage-android/src/main/java/com/joinforage/forage/android/network/TokenizeCardService.kt
- forage-android/src/main/java/com/joinforage/forage/android/network/data/CapturePaymentRepository.kt
- forage-android/src/main/java/com/joinforage/forage/android/network/data/CheckBalanceRepository.kt
- forage-android/src/main/java/com/joinforage/forage/android/ui/ForagePANEditText.kt
- forage-android/src/main/java/com/joinforage/forage/android/ui/ForagePINEditText.kt
Added trace IDs to the Android SDK and improved the current log schema with prefixes. The prefixes are naive at this point and should be adjusted to comply with DRY. Also, I added some extra pieces of data to the VGS logs.
Tested locally and verified in Datadog.
> [FX-385] Add trace ID to Android SDK, naive prefixes to logs, and data to VGS calls

- forage-android/src/main/java/com/joinforage/forage/android/ui/BTVaultWrapper.kt
- forage-android/src/main/java/com/joinforage/forage/android/ui/ForagePINEditText.kt
- forage-android/src/main/java/com/joinforage/forage/android/ui/VGSVaultWrapper.kt
- forage-android/src/main/res/values/attrs.xml
- sample-app/src/main/res/layout/fragment_catalog.xml
Fix the naming convention of publicly accessible fields.
- ❌ I've added unit tests for this change.
- ❌ The reviewer should manually test the changes in this PR.
> [FX-523] Fix height and width attribute naming convention

- forage-android/src/main/java/com/joinforage/forage/android/ui/BTVaultWrapper.kt
- forage-android/src/main/java/com/joinforage/forage/android/ui/ForageElement.kt
- forage-android/src/main/java/com/joinforage/forage/android/ui/ForagePANEditText.kt
- forage-android/src/main/java/com/joinforage/forage/android/ui/ForagePINEditText.kt
- forage-android/src/main/java/com/joinforage/forage/android/ui/VGSVaultWrapper.kt
- forage-android/src/main/res/values/attrs.xml
- sample-app/src/main/res/values/styles.xml
Adjust the naming convention and fix the styles that Milos added so they are ready for release.
> Adjust naming convention

- README.md
Update the public-facing README.md so that it reflects the latest state of the Android SDK v3
It's gotten very stale.
We'll want to merge this in last since so that it reflects the current repo instead of proceeds any changes
> Update the README.md to be in sync with V3 changes

- README.md
- forage-android/build.gradle
- forage-android/src/main/java/com/joinforage/forage/android/ForageSDK.kt
- forage-android/src/main/java/com/joinforage/forage/android/ForageSDKInterface.kt
- forage-android/src/main/java/com/joinforage/forage/android/LDManager.kt
- forage-android/src/main/java/com/joinforage/forage/android/collect/BTPinCollector.kt
- forage-android/src/main/java/com/joinforage/forage/android/collect/VGSPinCollector.kt
- forage-android/src/main/java/com/joinforage/forage/android/core/EnvConfig.kt
- forage-android/src/main/java/com/joinforage/forage/android/core/Log.kt
- forage-android/src/main/java/com/joinforage/forage/android/core/StopgapGlobalState.kt
- forage-android/src/main/java/com/joinforage/forage/android/network/ForageConstants.kt
- forage-android/src/main/java/com/joinforage/forage/android/ui/AbstractForageElement.kt
- forage-android/src/main/java/com/joinforage/forage/android/ui/ForagePANEditText.kt
- forage-android/src/main/java/com/joinforage/forage/android/ui/ForagePINEditText.kt
- sample-app/src/main/java/com/joinforage/android/example/ui/catalog/CatalogFragment.kt
- sample-app/src/main/res/values/styles.xml
This PR represents [Milestone 3](https://www.notion.so/joinforage/Plan-for-On-Time-Delivery-of-Android-3-0-Breaking-Changes-226d8ee6f8294d2694b1bb451791960b?pvs=4#66bf627d0ad34c50be03b8a002604f92) of the plan to deliver Android v3 changes to GoPuff by today
Reference the commit messages for a commit-by-commit breakdown of the code decisions that were made here.
- ❌ I've added unit tests for this change. In the interest of expediency, we could get some fundamental confidence from the qa-tests passing and defer proper unit tests as tech debt
- ✅ The reviewer should manually test the changes in this PR. Yes, please do! This is the last of the Android v3 BREAKING changes so please test to your heart's content!
https://github.com/teamforage/forage-android-sdk/assets/12377418/fc9c1c47-5b94-49e9- …
> Milestone 3 - Replace BuildConfig.FLAVOR with Stopgap FLAVOR

- README.md
- forage-android/build.gradle
- forage-android/src/main/java/com/joinforage/forage/android/ForageSDK.kt
- forage-android/src/main/java/com/joinforage/forage/android/ForageSDKInterface.kt
- forage-android/src/main/java/com/joinforage/forage/android/LDManager.kt
- forage-android/src/main/java/com/joinforage/forage/android/collect/BTPinCollector.kt
- forage-android/src/main/java/com/joinforage/forage/android/collect/VGSPinCollector.kt
- forage-android/src/main/java/com/joinforage/forage/android/core/EnvConfig.kt
- forage-android/src/main/java/com/joinforage/forage/android/core/Log.kt
- forage-android/src/main/java/com/joinforage/forage/android/core/StopgapGlobalState.kt
- forage-android/src/main/java/com/joinforage/forage/android/network/ForageConstants.kt
- forage-android/src/main/java/com/joinforage/forage/android/ui/AbstractForageElement.kt
- forage-android/src/main/java/com/joinforage/forage/android/ui/ForagePANEditText.kt
- forage-android/src/main/java/com/joinforage/forage/android/ui/ForagePINEditText.kt
- forage-android/src/test/java/com/joinforage/forage/android/core/env/EnvConfigTest.kt
- sample-app/src/main/java/com/joinforage/android/example/ui/catalog/CatalogFragment.kt
- sample-app/src/main/res/values/styles.xml
This is the PR for [Milestone 2](https://www.notion.so/joinforage/Plan-for-On-Time-Delivery-of-Android-3-0-Breaking-Changes-226d8ee6f8294d2694b1bb451791960b?pvs=4#f7302e2ba6df42fc80cd67c6e36f1fa9) of the plan to ship Android v3 to GoPuff by tomorrow EOD
We will need to temporarily rely on global state (via singleton) to ship Android v3 public contract changes ASAP without getting to [all of the required internal changes](https://www.notion.so/joinforage/Android-3-0-Design-Proposal-1ee6be95544d4dc78e7a7e7c88f46bbc?pvs=4#deb5c9f46bf74da9abc18f0b5f5ea4f4).
- ✅ I've added unit tests for this change. Specifically, I've added tests for the parsing session token logic
- ❌ The reviewer should NOT manually test the changes in this PR. This PR does not change any observable behavior. Those changes …
> Milestone 2 - Introduce `StopgapGlobalState`

- forage-android/build.gradle
- gradle.properties
Bump package major version to v3.0.0
> bump major version to v3.0.0

- sample-app/src/main/res/values/styles.xml
Fix copy-paste mistake where we try to set the wrong style value for the PIN field in the sample app
> [FX-583] Fix style bug in sample app

- forage-android/build.gradle
- gradle.properties
> bump to v3.0.0

- forage-android/build.gradle
- forage-android/src/main/java/com/joinforage/forage/android/ui/AbstractForageElement.kt
- gradle.properties
> Bump to version 3.1.0

- .github/workflows/Alert.yaml
- .github/workflows/CI.yaml
Run the CI test suite every day at 8 AM eastern in an attempt to pick up any errors in the Android SDK package that could be introduced by Payments-API.
> [FX-587] Run the CI job every day at 8 am Eastern

- .github/workflows/CI.yaml
- .github/workflows/Coverage.yaml
- .github/workflows/Lint.yaml
- .gitignore
- CONTRIBUTING.md
- build.gradle
- buildSrc/build.gradle.kts
- buildSrc/src/main/kotlin/com/joinforage/ShadowAarDependenciesPlugin.kt
- forage-android/build.gradle
- forage-android/src/main/java/com/joinforage/forage/android/core/telemetry/Log.kt
- sample-app/build.gradle
Creates a custom Gradle Plugin that leverages the [Shadow Gradle Plugin](https://github.com/johnrengelman/shadow) to relocate an arbitrary AAR (e.g. datadog in our case) to a custom package namespace.
We want to continue using Datadog for our own analytics and telemetry. However, the current major version 1 of Datadog android uses a singleton pattern that ultimately leaks logs between us and merchants. The most straightforward next step was to install Datadog major version 2; however, this version has class name collisions with Datadog Major version 1 since a lot of code is shared between the v1 and v2.
We must move our datadog package into a new namespace to get around these class name collisions. This PR uses the Shadow Gradle Plugin to programmatically relocate the datadog v2 AAR to a …
> Use datadog v2 in Log.kt

- forage-android/build.gradle
> Bump to v3.4.0

- README.md
Apologies for the duplicate PR. I've run into trouble signing my commits, but we should be good now. This PR solves the same problem discussed in [this Slack thread](https://joinforage.slack.com/archives/C056QGRF6S3/p1698971208622769?thread_ts=1694464266.125939&cid=C056QGRF6S3). 
We should over-communicate FNS' new requirements to prevent customer frustration. 
- ❌ Not a front end change 
- ✅  I previewed the markdown in VSCode 
N/A 
N/A
> [TW-338] Update Android Readme with callout

- README.md
- forage-android/build.gradle
bump version for release. Started including the version number in the README
> Bump to v3.5.0

- sample-app/src/main/java/com/joinforage/android/example/ui/complete/flow/balance/FlowBalanceFragment.kt
- sample-app/src/main/java/com/joinforage/android/example/ui/complete/flow/balance/FlowBalanceViewModel.kt
- sample-app/src/main/res/layout/fragment_flow_balance.xml
Let a user of the sample app skip the balance check to speed up qa-tests
> Add ability to skip balance check in sample app

- README.md
- forage-android/build.gradle
Bump from version 3.5.0 to 3.6.0
> Bump to version 3.6.0

- README.md
- forage-android/src/main/java/com/joinforage/forage/android/ForageSDKInterface.kt
- forage-android/src/main/java/com/joinforage/forage/android/model/PaymentMethod.kt
- forage-android/src/main/java/com/joinforage/forage/android/network/TokenizeCardService.kt
- forage-android/src/main/java/com/joinforage/forage/android/network/model/PaymentMethodRequestBody.kt
- forage-android/src/test/java/com/joinforage/forage/android/fixtures/CreatePaymentMethodFixtures.kt
- forage-android/src/test/java/com/joinforage/forage/android/network/TokenizeCardServiceTest.kt
- forage-android/src/test/resources/fixtures/payment/methods/successful_create_payment_method_without_customer_id.json
- sample-app/src/main/java/com/joinforage/android/example/network/model/tokenize/PaymentMethod.kt
- Make `customerId` in `tokenizeEBTCard` method optional
- ✅  Added unit tests for missing `customerId` case
Can be released as-is
> [FX-313] Make customerId optional

- forage-android/src/main/java/com/joinforage/forage/android/collect/BTPinCollector.kt
- forage-android/src/main/java/com/joinforage/forage/android/collect/PinCollector.kt
- forage-android/src/main/java/com/joinforage/forage/android/collect/VGSPinCollector.kt
- forage-android/src/main/java/com/joinforage/forage/android/network/ForageConstants.kt
- forage-android/src/main/java/com/joinforage/forage/android/network/data/BaseVaultRequestParams.kt
- forage-android/src/main/java/com/joinforage/forage/android/network/data/CapturePaymentRepository.kt
- forage-android/src/main/java/com/joinforage/forage/android/network/data/CheckBalanceRepository.kt
- forage-android/src/main/java/com/joinforage/forage/android/network/data/DeferPaymentCaptureRepository.kt
- forage-android/src/main/java/com/joinforage/forage/android/pos/PosVaultRequestParams.kt
- forage-android/src/test/java/com/joinforage/forage/android/network/data/CapturePaymentRepositoryTest.kt
- forage-android/src/test/java/com/joinforage/forage/android/network/data/CheckBalanceRepositoryTest.kt
- forage-android/src/test/java/com/joinforage/forage/android/network/data/DeferPaymentCaptureRepositoryTest.kt
- forage-android/src/test/java/com/joinforage/forage/android/network/data/TestPinCollector.kt
- Add support for generic `BaseVaultRequestParams`
- Easier to support pos-specific params while reusing existing facilities
- ✅ Updated unit tests to use the new generic params
Can be merged as-is and other branches for POS refund + balance will build on top of these changes
> Support generic vault request params

- forage-android/src/main/java/com/joinforage/forage/android/ForageSDK.kt
- forage-android/src/main/java/com/joinforage/forage/android/LDManager.kt
- forage-android/src/main/java/com/joinforage/forage/android/collect/AbstractVaultSubmitter.kt
- forage-android/src/main/java/com/joinforage/forage/android/collect/BasisTheoryPinSubmitter.kt
- forage-android/src/main/java/com/joinforage/forage/android/collect/PinCollector.kt
- forage-android/src/main/java/com/joinforage/forage/android/collect/VaultProxyRequest.kt
- forage-android/src/main/java/com/joinforage/forage/android/collect/VgsPinSubmitter.kt
- forage-android/src/main/java/com/joinforage/forage/android/core/telemetry/Metrics.kt
- forage-android/src/main/java/com/joinforage/forage/android/network/ForageConstants.kt
- forage-android/src/main/java/com/joinforage/forage/android/pos/ForageTerminalSDK.kt
- forage-android/src/main/java/com/joinforage/forage/android/pos/PosMethodParams.kt
- forage-android/src/main/java/com/joinforage/forage/android/pos/PosRefundPaymentRepository.kt
- forage-android/src/main/java/com/joinforage/forage/android/pos/PosRefundService.kt
- forage-android/src/main/java/com/joinforage/forage/android/pos/PosRefundVaultResponse.kt
- forage-android/src/main/java/com/joinforage/forage/android/pos/PosVaultRequestParams.kt
- forage-android/src/main/java/com/joinforage/forage/android/ui/BTVaultWrapper.kt
- forage-android/src/main/java/com/joinforage/forage/android/ui/ForagePINEditText.kt
- forage-android/src/main/java/com/joinforage/forage/android/ui/ForageVaultWrapper.kt
- forage-android/src/main/java/com/joinforage/forage/android/ui/VGSVaultWrapper.kt
- forage-android/src/main/java/com/joinforage/forage/android/ui/VaultWrapper.kt
- forage-android/src/test/java/com/joinforage/forage/android/pos/ForageTerminalSDKTest.kt
- makes some slight modifications to the Abstract vault submitters to make them compatible with POS
- implements new refundPayment method
- updates Kdoc comments
Can be merged as-is!
> [FX-813] Implement refundPayment for POS

- .idea/misc.xml
- sample-app/src/main/java/com/joinforage/android/example/ui/pos/network/PosApiService.kt
Previously we the endpoint was `GET api/merchants`. Now it's `GET api/merchants/`
Payments API was returning a 301
Can be merged straight away
> Add trailing stash to GET /api/merchants

- forage-android/src/main/java/com/joinforage/forage/android/pos/ForageTerminalSDK.kt
- forage-android/src/main/java/com/joinforage/forage/android/pos/PosMethodParams.kt
- forage-android/src/main/java/com/joinforage/forage/android/pos/PosRefundPaymentRepository.kt
- forage-android/src/main/java/com/joinforage/forage/android/pos/PosVaultRequestParams.kt
- Use more logical param ordering
- Prefix POS-specific params with `Pos`
> Fix POS refund params

- sample-app/src/main/java/com/joinforage/android/example/ui/pos/POSComposeApp.kt
- sample-app/src/main/java/com/joinforage/android/example/ui/pos/screens/BalanceResultScreen.kt
- sample-app/src/main/java/com/joinforage/android/example/ui/pos/screens/PinEntryScreen.kt
- sample-app/src/main/res/values/strings.xml
Creates a screen to show the results of a balance inquiry. Tapping "Done" takes you back to the action selection screen
POS Cert App
https://github.com/teamforage/forage-android-sdk/assets/11556475/0e605020-80ea-4551-b0fc-4a01536f8871
> [FX-817] Make a balance inquiry results screen

- README.md
This PR adds details to the README.md about new Forage functionality. It also edits some of the existing information, for example about Element types and how to style them. 
The goal of improving documentation is to make it easier to use the SDK. 
- ✅ |  I've added unit tests for this change. 
Check out my branch and review the README.md. 
N/A
I'll open a PR to revert the change if things break!
> [TW-425] Update README.md

- forage-android/src/main/java/com/joinforage/forage/android/ui/ForageElement.kt
This PR updates comments for ForageConfig and setForageConfig. 
Improving documentation hopefully makes the SDK easier to use. 
- ❌ |  No unit tests, because this PR only changes comments. 
- ✅ |  The reviewer should manually test the changes in this PR. 
To test, checkout my branch and run: 
```
.gradlew dokkaHtml
```
> [TW-396] Update ForageConfig and setForageConfig kDoc comments

- forage-android/src/main/java/com/joinforage/forage/android/ForageSDKInterface.kt
This PR updates the comments for Params models for ForageSDK. 
The goal of improving comments is to improve documentation and make the SDK easier to use.
> [TW-401] Update comments for Params models

- forage-android/src/main/java/com/joinforage/forage/android/ui/ForageElement.kt
This PR adds comments to the ForageElement methods. 
The goal of these comments are to better document the SDK so that it is easier to use. 
- ❌ |  No unit tests are needed for strictly comment changes. 
- ✅ | The reviewer should manually test the changes in this PR: 
Checkout my branch, and then run: 
```
./gradlew dokkaHtml 
```
> [TW-397] Update comments for ForageElement

- sample-app/src/main/java/com/joinforage/android/example/ui/pos/POSComposeApp.kt
- sample-app/src/main/java/com/joinforage/android/example/ui/pos/POSViewModel.kt
- sample-app/src/main/java/com/joinforage/android/example/ui/pos/data/POSUIState.kt
- sample-app/src/main/java/com/joinforage/android/example/ui/pos/data/Refund.kt
- sample-app/src/main/java/com/joinforage/android/example/ui/pos/network/PosApiService.kt
- sample-app/src/main/java/com/joinforage/android/example/ui/pos/screens/ActionSelectionScreen.kt
- sample-app/src/main/java/com/joinforage/android/example/ui/pos/screens/refund/RefundDetailsScreen.kt
- sample-app/src/main/java/com/joinforage/android/example/ui/pos/screens/refund/RefundResultScreen.kt
- sample-app/src/main/res/values/strings.xml
Adds a flow to support refunding payments. Here's [an example of a refund created through the android emulator](https://api.dev.joinforage.app/admin/api/refund/2407/change/) in dev.
https://linear.app/joinforage/issue/FX-746/story-snap-cash-return-refund-flow
- ❌ Early scaffolding of basic functionality
- ❌ Demo video should be sufficient
https://github.com/teamforage/forage-android-sdk/assets/11556475/85ce4ac7-429c-4d88-bda9-f2ba2fce7d14
> [FX-746] Story: Return or refund a transaction

- forage-android/src/main/java/com/joinforage/forage/android/network/model/ForageApiResponse.kt
This PR adds comments to `ForageAPIResponse.kt`, with the goal of improving the documentation for Forage Errors. 
@dleis612 , hi! @djoksimo and I discussed this one IRL 🥳 , and we thought that `ForageApiError` and `ForageErrorObj` should be `internal`, so this PR adds that too. Please let me know of any objections? 
Better docs -> More merchants onboard faster. 
Check out my branch and run: 
```
```
> [TW-402] Update comments for ForageAPiError

- forage-android/src/main/java/com/joinforage/forage/android/ui/AbstractForageElement.kt
This PR adds a private tag to the `AbstractForageElement` class. 
Reduces developer confusion. 
- ❌ | Unit tests are not required for docs changes 
- ✅ | I tested my changes locally 
- ✅ | ❌ The reviewer should manually test the changes in this PR. 
Check out my branch and run:
```
```
> [TW-404] Add comment that AbstractForageElement is internal

- forage-android/src/main/java/com/joinforage/forage/android/ui/ForagePANEditText.kt
- forage-android/src/main/java/com/joinforage/forage/android/ui/ForagePINEditText.kt
This PR adds a comment to describe each `ForagePANEditText` and `ForagePINEditText`, and links to the relevant methods. 
Improving the docs -> better developer experience. 
- ❌ | No unit tests for docs changes. 
- ✅ | I previewed the change locally.  
- ✅ |  The reviewer should manually test the changes in this PR. 
```
```
> [TW-398] Update comments for ForagePANEditText and ForagePINEditText

- forage-android/src/main/java/com/joinforage/forage/android/ForageSDKInterface.kt
- forage-android/src/main/java/com/joinforage/forage/android/core/element/ElementValidationErrors.kt
- forage-android/src/main/java/com/joinforage/forage/android/network/model/Message.kt
This PR updates comments for errors, and adds an internal tag to what is maybe a helpful for a `toString` function. 
Improving the comments that will be used to generate documentation will help make the SDK easier to use. 
- ❌ | No unit tests are needed for comment changes 
Checkout my branch. 
Run: 
```
```
> [TW-420] Update comments for errors 

- .github/CODEOWNERS
Evan has earned his Android stripes (and Danny is OOO this week). Adding him as a code owner
> Add Evan as a CODEOWNER

- forage-android/src/main/java/com/joinforage/forage/android/ForageSDK.kt
- forage-android/src/main/java/com/joinforage/forage/android/pos/ForageTerminalSDK.kt
- forage-android/src/main/java/com/joinforage/forage/android/pos/PosMethodParams.kt
This PR adds comments for TerminalSDK methods and models (excluding the upcoming `init` change, to be discussed with Devin tomorrow). 
Improving docs comments improves the usability of the SDK. 
-  ❌ | Unit tests are not required for comment changes. 
```
```
> [TW-442] Update comments for TerminalSDK

- sample-app/src/main/java/com/joinforage/android/example/pos/receipts/templates/txs/TxReceiptTemplate.kt
- sample-app/src/main/java/com/joinforage/android/example/ui/pos/POSViewModel.kt
- sample-app/src/main/java/com/joinforage/android/example/ui/pos/data/PosReceipt.kt
> [FX-1093] Support not having a balance on the receipt

- README.md
This PR adds changes to the README.md that document the upcoming `init` function. It also adds documentation for `setPosForageConfig`.
> [TW-477] Update README to include init docs

- README.md
- forage-android/build.gradle
Release deferred refund endpoint for Toast.
> Bump to version 3.8.0

- README.md
This PR adds the deferPaymentRefund updates to the README.md. 
All methods are currently documented in the README.md, so this updates documentation. 
- ✅ | No unit tests for README.md changes. 
-  ❌ | The reviewer should manually test the changes in this PR.
> [TW-480] Update README to include deferPaymentRefund

- forage-android/src/main/java/com/joinforage/forage/android/core/element/state/ElementState.kt
- forage-android/src/main/java/com/joinforage/forage/android/model/StateIIN.kt
This PR updates comments for states, derivedCardInfo, and USState. 
These comments will eventually serve as customer-facing docs. 
- ❌ | Tests aren't needed for comment changes. 
```
```
> [TW-406] Update comments for states, derivedCardInfo, USState

- README.md
- forage-android/src/main/java/com/joinforage/forage/android/ForageSDK.kt
- forage-android/src/main/java/com/joinforage/forage/android/ForageSDKInterface.kt
- forage-android/src/main/java/com/joinforage/forage/android/core/element/ElementValidationErrors.kt
- forage-android/src/main/java/com/joinforage/forage/android/model/StateIIN.kt
- forage-android/src/main/java/com/joinforage/forage/android/network/model/ForageApiResponse.kt
- forage-android/src/main/java/com/joinforage/forage/android/network/model/Message.kt
- forage-android/src/main/java/com/joinforage/forage/android/pos/ForageTerminalSDK.kt
- forage-android/src/main/java/com/joinforage/forage/android/pos/PosMethodParams.kt
- forage-android/src/main/java/com/joinforage/forage/android/ui/ForagePANEditText.kt
- forage-android/src/main/java/com/joinforage/forage/android/ui/ForagePINEditText.kt
This PR adds most of the feedback that Danilo and I discussed in real-time on March 4, 2024. 
Any exceptions are noted in the "Notes" section of the Linear ticket.
These small stylistic edits and typo fixes make the docs easier to digest.
- ❌ | No unit tests are needed for comment changes. 
```
```
> [TW-524] Add March 4 2024 edits

- CONTRIBUTING.md
This PR removes `Dev` from the unit test command because the tests fail unless `Dev` is removed. 
This fix makes for an improved contributor experience. 
- ❌ | I've added unit tests for this change. 
- ❌ | The reviewer should manually test the changes in this PR. 
No unit tests required for a CONTRIBUTING.MD change, though I did make sure that the command that I updated this to runs.
> [TW-412] Update CONTRIBUTING.md unit test command

- forage-android/src/main/java/com/joinforage/forage/android/ForageSDK.kt
- forage-android/src/main/java/com/joinforage/forage/android/ForageSDKInterface.kt
- forage-android/src/main/java/com/joinforage/forage/android/pos/ForageTerminalSDK.kt
- forage-android/src/main/java/com/joinforage/forage/android/ui/ForageElement.kt
- forage-android/src/main/java/com/joinforage/forage/android/ui/ForagePANEditText.kt
- forage-android/src/main/java/com/joinforage/forage/android/ui/ForagePINEditText.kt
This PR adds code snippets to the example Elements and methods for the Android SDKs. It also adds links to the relevant Quickstarts in a few more places, and fixes an errant nested bullet. 
Code samples will make it easier for developers to copy/paste while reading the auto-generated docs. 
- ❌ | Unit tests are not required for comment changes. 
```
```
> [TW-415] Add sample code to Android SDK comments

- forage-android/src/main/java/com/joinforage/forage/android/Utils.kt
Make internal-use-only extension/util `internal`
> Make addPathSegmentSafe internal

- README.md
- forage-android/build.gradle
Bump minor version 
N/A
N/A
Merge this once we merge in the `showKeyboard()` PR
> Bump to v3.9.0

- sample-app/src/main/java/com/joinforage/android/example/ui/complete/flow/payment/capture/FlowCapturePaymentViewModel.kt
- sample-app/src/main/java/com/joinforage/android/example/ui/complete/flow/payment/capture/model/FlowCapturePaymentUIState.kt
- sample-app/src/main/java/com/joinforage/android/example/ui/complete/flow/payment/create/FlowCreatePaymentFragment.kt
- sample-app/src/main/java/com/joinforage/android/example/ui/complete/flow/payment/create/FlowCreatePaymentViewModel.kt
- sample-app/src/main/res/layout/fragment_flow_capture_payment.xml
- sample-app/src/main/res/layout/fragment_flow_create_payment.xml
- sample-app/src/main/res/navigation/mobile_navigation.xml
Add path to set the payment ref directly on the UI.
For qa-tests!
> [FX-1365] Add new path to add a Payment ref to UI

- sample-app/src/main/java/com/joinforage/android/example/ui/complete/flow/balance/FlowBalanceFragment.kt
- sample-app/src/main/java/com/joinforage/android/example/ui/complete/flow/tokenize/FlowTokenizeFragment.kt
> [FX-1516] Fix isFocused state in sample app

- README.md
- forage-android/build.gradle
Bump Android SDK to the new Major 4 version. 
Should only be merged after #277
> Bump to v4

- README.md
- forage-android/build.gradle
> Bump to v4.0.1

- forage-android/src/main/java/com/joinforage/forage/android/ecom/services/ForageSDK.kt
- forage-android/src/main/java/com/joinforage/forage/android/ecom/ui/element/ForagePINEditText.kt
Apply spotless to `main` 
`main` wasn't passing the linter check which was affecting other PRs
N/A
N/A
Release immediately to not block other PRs
> Appease Spotless

- requirements.txt
Title
See Snyk output here: https://app.snyk.io/org/forage/project/8aa6e468-dae6-4911-aaee-c63fe7a4ca65#issue-SNYK-PYTHON-SETUPTOOLS-7448482
> [SEC-37] Pin setuptools to appease Snyk

- forage-android/build.gradle
Bump BT to `v4.2.2`
It's best practice to keep security related dependencies up to date
CI test's pass
- ✅ The reviewer should manually test the changes in this PR. You can if you want!
N/A
Can be released immediately
> Bump BT to latest version

- forage-android/build.gradle
> Bump to 4.1.0

- build.gradle
> [DOC-879] Fix the footer of Android docs

- forage-android/src/main/java/com/joinforage/forage/android/core/ui/element/ForagePanElement.kt
- forage-android/src/main/java/com/joinforage/forage/android/ecom/services/ForageSDK.kt
- sample-app/src/main/java/com/joinforage/android/example/ui/complete/flow/tokens/FlowTokensFragment.kt
- sample-app/src/main/java/com/joinforage/android/example/ui/complete/flow/tokens/TokensViewModel.kt
- sample-app/src/main/res/layout/fragment_flow_tokenize.xml
- sample-app/src/main/res/values/themes.xml
Small fixes and refactorings.
In preparation for larger changes for upcoming credit card payment sheet.
No new unit test coverage needed.
> [EXPA-207] Small fixes and refactorings

- forage-android/src/main/java/com/joinforage/forage/android/core/ui/textwatcher/ExpirationTextWatcher.kt
- forage-android/src/main/java/com/joinforage/forage/android/core/ui/textwatcher/TextWatcherAdapter.kt
- forage-android/src/test/java/com/joinforage/forage/android/core/ui/textwatcher/ExpirationTextWatcherTest.kt
- forage-android/src/test/java/com/joinforage/forage/android/ecom/ui/textwatcher/TextWatcherAdapterTest.kt
Implement ExpirationTextWatcher.
Automatically insert a slash into a MM/YY text input.
Unit testing
> [EXPA-214] Implement ExpirationTextWatcher

- forage-android/build.gradle
- forage-android/src/main/java/com/joinforage/forage/android/ecom/ui/element/ForagePaymentSheet.kt
- forage-android/src/main/res/layout/forage_payment_sheet.xml
- forage-android/src/main/res/values/attrs.xml
- forage-android/src/main/res/values/strings.xml
- forage-android/src/test/java/com/joinforage/forage/android/ecom/ui/element/ForagePaymentSheetTest.kt
- forage-android/src/test/java/com/joinforage/forage/android/mock/MockForagePaymentSheet.kt
Implement ForagePaymentSheet fragment.
Unit testing
> [EXPA-215] Implement ForagePaymentSheet fragment

- sample-app/src/main/java/com/joinforage/android/example/data/PaymentsRepository.kt
- sample-app/src/main/java/com/joinforage/android/example/network/ForageApi.kt
- sample-app/src/main/java/com/joinforage/android/example/network/model/Address.kt
- sample-app/src/main/java/com/joinforage/android/example/network/model/AuthorizeRequest.kt
- sample-app/src/main/java/com/joinforage/android/example/network/model/CaptureRequest.kt
- sample-app/src/main/java/com/joinforage/android/example/network/model/PaymentRequest.kt
- sample-app/src/main/java/com/joinforage/android/example/network/model/PaymentResponse.kt
- sample-app/src/main/java/com/joinforage/android/example/ui/complete/flow/payment/capture/FlowCaptureCreditPaymentFragment.kt
- sample-app/src/main/java/com/joinforage/android/example/ui/complete/flow/payment/capture/FlowCaptureCreditPaymentViewModel.kt
- sample-app/src/main/java/com/joinforage/android/example/ui/complete/flow/payment/create/FlowCreateCreditPaymentFragment.kt
- sample-app/src/main/java/com/joinforage/android/example/ui/complete/flow/payment/create/FlowCreateCreditPaymentViewModel.kt
- sample-app/src/main/java/com/joinforage/android/example/ui/complete/flow/payment/create/FlowCreatePaymentFragment.kt
- sample-app/src/main/java/com/joinforage/android/example/ui/complete/flow/payment/create/FlowCreatePaymentViewModel.kt
- sample-app/src/main/java/com/joinforage/android/example/ui/complete/flow/tokenize/FlowTokenizePaymentSheetFragment.kt
- sample-app/src/main/java/com/joinforage/android/example/ui/complete/flow/tokenize/FlowTokenizeViewPaymentSheetViewModel.kt
- sample-app/src/main/java/com/joinforage/android/example/ui/complete/flow/tokens/FlowTokensFragment.kt
- sample-app/src/main/res/layout/fragment_flow_capture_credit_payment.xml
- sample-app/src/main/res/layout/fragment_flow_create_credit_payment.xml
- sample-app/src/main/res/layout/fragment_flow_tokenize_credit.xml
- sample-app/src/main/res/layout/fragment_flow_tokens.xml
- sample-app/src/main/res/menu/bottom_nav_menu.xml
- sample-app/src/main/res/navigation/mobile_navigation.xml
- sample-app/src/main/res/values/strings.xml
Extend sample-app for HSA/FSA
Observation
> [EXPA-217] Extend sample-app for HSA/FSA

- forage-android/src/main/res/drawable/editable_frame.xml
- forage-android/src/main/res/layout/forage_payment_sheet.xml
Style to match Gopuff appearance
Inspection
> [EXPA-237] Style to match Gopuff appearance

- forage-android/src/main/java/com/joinforage/forage/android/core/ui/element/ForageElement.kt
- forage-android/src/main/java/com/joinforage/forage/android/core/ui/element/ForagePanElement.kt
- forage-android/src/main/java/com/joinforage/forage/android/core/ui/element/ForagePinElement.kt
- forage-android/src/test/java/com/joinforage/forage/android/ecom/ui/element/ForagePANEditTextTest.kt
- forage-android/src/test/java/com/joinforage/forage/android/mock/TestForagePANEditText.kt
Add missing @ColorInt annotations.
Also fix parameter name to setBoxStrokeWidthFocused.
Unit testing
> [EXPA-240] Add missing @ColorInt annotations

- forage-android/src/main/java/com/joinforage/forage/android/ecom/services/ForageSDK.kt
- forage-android/src/main/java/com/joinforage/forage/android/ecom/ui/element/ForagePaymentSheet.kt
- forage-android/src/main/res/drawable/editable_frame.xml
- forage-android/src/main/res/values/colors.xml
- forage-android/src/main/res/values/dimens.xml
- forage-android/src/test/java/com/joinforage/forage/android/ecom/services/ForageSDKTest.kt
- forage-android/src/test/java/com/joinforage/forage/android/ecom/ui/element/ForagePaymentSheetTest.kt
Introduce ForagePaymentSheetField.
This design better reflects what we have in our iOS SDK.
Unit testing
> [EXPA-241] Introduce ForagePaymentSheetField

- forage-android/build.gradle
Update Android pom developer metadata.
Best practices
No code changes
> [EXPA-326] Update Android POM developer metadata
